Jiff,
	Would you believe that I became dyslexic ? I will try
    and stay consistent.


RECOVERY TIME

	Jiff, I no longer have the tape but I do have the data left
    over from the analysis. 

           Recovery (expressed as a percentage of the total strike time)
           -------------------------------------------------------------
Shoto
Kick       26%

Shoto 
Punch      48%


Uechi
Kick      50%


Uechi
Punch    49%


Before you jump on some of this data as overly significant. Keep in 
mind that the Shotokan Kick took almost twice as long (1.4 secs) and 
traveled twice the distance of the Uechi Kick.

I have an article on fencing lunges that I will trying and dig out.

DAMAGE VS SPEED
	
This is really much messier than it looks on the surface. 
Increasing the speed increases the energy , thus the damage !
But, there are definite cases where stopping and doing a more
deliberate strike can bring in a great deal more energy.

KATA

Jiff, I was fighting against any simplification of Alixsanta's 
handling of kata. I think they are fairly balanced now. At
least from my limited experience with Menahan.

PRESSING

I guess I have real problems with describing any style as being
in a permanent state such as fighting in a press. I feel that
the press condition is so subject to who the opponents are that
it gets silly to characterize. Ideally you would model this by 
saying that the Uechi person is trying to close in order to get 
into range to punch. The shotokan person fails to see this and 
the Uechi person closes and bites his throat out. Yumm. ;-)

I think that a having someone inside your optimal range for 
weapon use does indeeed lower you chance to use your weapon 
effectively. I would even go so far as to say that in many 
cases it may be safer to drop your sword and grapple with a 
dagger person who has gotten in under your blade.

RETREAT

I guess I am asking what people thinks happens in a retreat.
Does the person sense that their opponent is getting closer, 
and then just back off to stay out of range ? Does the 
character see that an opponent is taking his time reacting
and back off ? I am not sure that it is even possible to 
casually retreat to a safe distance in BT. Physical movement
is much slower than punches in BT. Yet I know I can casually 
retreat against someone of equal skill in a sparring match 
because I have done it.

GRAPPLE/OVERBEAR

I am stuck in this horrible muddle of having to jump up and
down and say over and over "There is a difference, and it is
worth modeling" yet being unable to explain why.

I think the closest I can come is that overbears involve
the manipulation of momentum via the attackers strength and 
Physical agility while grappling involves the manipulation 
of momentum via Dex and Agil. I also think that the forces 
generated by grapple throws are greater than those for Overbear
throws. Typical judo throws involve forces 2.5 times greater
than the combined masses of the individuals involved. A football
tackle is physically different because it is typically a 
moving collision that focuses on the forces involved in 
the point of impact. I am saying this badly. Argggggggggg

Perhaps it is worth modeling a relationship between the two.

MARTIAL ARTS

sidekick=roundhouse=crescent. The damage and the total strike
tikes are within 5% of each other. I will be sending out 
Mochel's Universal Damage Document soon and you can look at 
real (albeit, predigested) numbers.

Knfe/Ridge hand is not the same as a punch. The forces generated are 
different. It is the same as a hammerfist. 

ON SUPPORT SKILLS

Alex, have you completely burned out your proms ? What possible
reason can you give for punch to increase block ! That is what PCF
is for !

ON SKILL RELATIONSHIPS

In the discussion of General skills you referred to "Knowledge 
of a martial art" . Are we talkking Lore:Karate ? or are we 
talking the conglomerate of skills that make up a package called
karate ? !I! have yet to agree that they exist .

SUPPORT SKILLS

Those make perfect and utter sense. I really don't think that
they should be applied (Except via PCF) to any other skill
than that for which they are designed. Well, maybe. What
about quick strike punch skill being used with a quick strike 
palm heel ? But not with a quick strike kick.

SECONDARIES

Is the increase in effectiveness of all those skills the end result 
of all of them adding to his single design roll or the result of a 
number of actions including ( a quick search in his memory for previous 
similiar designs => lore skill, The roll to make the design => circuit design,
and the roll to make sure there are no practical problems with the design 
=> elect. ops. ). I agree that you do not want to specify all those 
actions just to make a circuit (I don't anyway) but I don't think that you 
can cleanly model a series of rolls by incremental pile ups of percemntages on 
a single roll this way. 

RADICAL CONCEPT

How about simply allowing skills that are linked together in some manner to 
create a special level factor for that bundle of skills. Sort of a variation
of TL with the advantage that you can avoid all the recalc involved in making
a single roll. Remember, Alex, that Menahan needs 8 rows and several columns
to add up all the skills and secondaries that apply to a single sword strike.

TERTIARIES/QUATERNARIES/QUINTENARIES

BAH, Humbug

PERCEPTION

If we are doing all those continous perception rolls that why not change 
your baseline to accomodate this the way you have with everyone being in a 
light retreat ? Then you only need worry about active perceptions.


SNAP-PY RETORTS

It is very unclear that torqing the hips at the last moment has any
serious influence on the speed and force of the strike. I can fill
the bandwidth with biomechanics notes on the concept but the end 
result is a resounding "Well, Maybe". The reports I give the most
credence to justify it on the basis that it cushions the impacts
effects on the kicker and may allow for a more solid stance at
the time of impact.


SWEEPS

They are distinctly different. A mere kick to the legs will rarely 
dislodge someone unless it is amazingly powerful. A sweep depends on
using the foot or leg to take control of someones center of balance 
and move it. (Less than 50 words !)

STANCES

Cat stance and Back stance are distinctly different ! I would not
attempt many of the things I can do from cat stance in back stance.

Also, there is a long low stance, distict from a crouch, that the 
White Dragon people use a lot. (Particularly for sweeps). I 
don't know the name of it but they were very fast getting in 
and out of it. Alex, do you know the name ? They had one leg
extended and one leg tucked under them. It is also used in Chai-Gerk.

Also, don't forget Sanchin Stance. Even those Shotokan People use it.
They will steal form anybody :-)))))))))))))) <- Big Grin


Jim 



 












	
