.so header.rof
.he //The Costs of Skills by Type//
.fo //Page #//
.in 5
.rm 71
.nf
.ce 1
Type of Skill
.sp 3
            Simple Skill        Craft       Art
        
Rank    
0           200                 250         300
1           75                  100         125
2           125                 200         300
3           300                 500         850
4           550                 950         1400
5           850                 1450        2200
6           1350                2050        3400
7           1700                2800        4200
8           2250                3600        5300
9           2900                6300        6800
10          3500                8000        9500
11+         6500                9000        1050
