H46583
s 00007/00000/00000
d D 1.1 02/01/08 23:03:37 jmochel 2 1
cF1
cK18906
cO-rw-rw-rw-
e
s 00000/00000/00000
d D 1.0 02/01/08 23:03:37 jmochel 1 0
c BitKeeper file g:/workspace/BardicTales/Cultures/culture.MAC
cBjmochel@devilmountain|ChangeSet|20001208143925|39592|56cfc6eb
cHdevilmountain
cK01650
cPCultures/culture.MAC
cR34565fa7
cV4
cX0x121
cZ-05:00
e
u
U
f e 1
f x 0x121
t
T
I 2
M544M36%C<F\Q &0  " @(" @(" @(" @(" @(" @ @  _R!)(&T@;R"'($L@
M,3<@,CD@2R S.2 S,S,@52 Q-R T.3$X,2!#(#8P(#4Q($,@,3$R(#(U($,@
M.3<@,S @0R Q,30@,3D@0R Y-R S,"!#(#8R(#4R($L@,S4@,S,U($,@-C @
M-3$@0R T-R U,R!#(#$Q,B R-2!#(#DW(#,P($,@,3$T(#$Y($,@.3<@,S @
M0R V,R U,R!#(#@@,30@0R V," U,2!#(#@@,30@0R V,B U,B!+(#0P(#,S
F-B!+(#,V(#,R-R!+(#,V(#,R-R!+(#$W(#(Y(%4@,3<@-#DQ.#$ 
 
E 2
I 1
E 1
