#!/bin/zsh

# Define keywords and their replacements

id=$(git rev-parse --short HEAD)
date=$(git log -1 --format=%cd --date=format:'%d/%m/%Y')
datetime=$(git log -1 --format=%cd --date=format:'%Y-%m-%d %H:%M:%S')
author=$(git log -1 --format=%an)
revision=$(git log -1 --format=%h)

# Perform keyword substitutiongit-keyword-filtergit-keyword-filter
sed -e "s/\$Id\$/$id/g" \
    -e "s/\$Date\$/$date/g" \
    -e "s/\$DateTime\$/$datetime/g" \
    -e "s/\$Author\$/$author/g" \
    -e "s/\$Revision\$/$revision/g" "$1"

