h44655
s 00105/00000/00000
d D 1.1 99/12/02 16:01:51 jmochel 2 1
cC
cK07241
cO-rw-rw-rw-
e
s 00000/00000/00000
d D 1.0 99/12/02 16:01:47 jmochel 1 0
c BitKeeper file G:/SpaceHybrid/worlds/ea/aurioch.nr
cBjmochel@devilmountain.bedford.foliage.com|ChangeSet|19991202203126|52994|e2968a7f5cb68f67
cHdevilmountain.bedford.foliage.com
cK45011
cPworlds/ea/aurioch.nr
cReb47867e5cb68f68
cZ-05:00
c______________________________________________________________________
e
u
U
f e 0
f x 33
t
T
I 2
.so header.rof
.he //The Deities of Ea - Aurioch//
.fo //Page #//
.in 9
.rm 71
.fi
.ce 2
Knight of Chaos
Knight of Swords
.sp 1
Symbol
.NP
Circle with Red Arrows radiating from it
.sp 1
Reality
.NP
Aurioch is a very difficult diety to follow or to understand.
Aurioch's greatest goal is to thwart almost all of the other deities
greatest goals. He has given up on Tempus (he has no idea what the Unseen
lords goal is !!), he is in a truce with Hekate (He is not sure that she
is not helping him by pursuing her own goals.), he does not bother
Kishijoten , nor does he usually bother Tiamat who is his creation. 
He particularly enjoys derailing Loki's works.
.sp 1
Churches Role
.NP           
The church of Aurioch is one of the strangest on the plane. Many of
the clerics are actively involved in power struggles with themselves and
the clerics of other churchs. They are considered very dangerous and their
martial arm is very feared by all. The clerics wear red and black and are
trained in the use of two handed swords. This two handed sword acts as a
holy symbol even though it is really the eight pointed star in the hilt
that is the holy symbol. The "Blades of Chaos" are the martial arm and are
trained in two handed sword as well. They are usually identified by their
capes (black outer/red inner) and their helms with a Aurioch Star on the
forehead. Another favoured weapon is the eight pointed throwing star or
"Aurioch Star". They are not adverse to using poison though usually not on
the two handed sword. Paladins of Aurioch are able to reverse their self
heal so that it damages others at twice the damage that it heals (ST for
1/2 damage). Monks of Aurioch tend to favor feet and large bladed staves.
.sp 1
Peoples View
.NP
The people fear the god and his church. They have been at many times
crushed by some scheme that was not aimed at them. 
.sp 1
Divine Intervention
.NP
If such an intervention should actually, by some bizarre set of
circumstance, occur then it will take the form of a hell hound or other
monster. 
.bp
Clerical Spells
.nf
T1	Detect Aura
T2	Talk To Creatures of Shadow

G1	Charming
G2	Wind Whistle
G3	Conjour Mist
G4	Water Creation	
G5	Heat Production
G6	Temperature Alteration
G7	Protection vs. Magical Fires
G8	Healing
G9	Detect Poison
G10	Shadowform
G11	Blending
G12	Strength of Shadow
G13	Walking Unseen

Q1	Augury
Q2	Draw Strength From Shadow

S1	Bolt of Chaos
S2	Spell of Opening
S3	Stormcallling
S4	Maelstrom
S5	Bolt of Fire
S6	Weapon of Flames
S7	Smoking Magma
S8	Bolt of Shadow
S9	Shadow Walking
S10	Fear
S11	Harming Entity
S12	Creating Shadow Sword

R1	Greater Prayer
.sp 2
.ce 1
The Litany to Aurioch
.sp 1
.NP
That wherever your domain extends thou shalt use your 
power for the greater glory of Aurioch. To this shall your 
guile and craft be pledged.
.NP 
That no being may restrict the lord Aurioch and that his domain
may grow shalt thou subvert order and it minions. To this shall
your guile and craft be pledged.
.NP
That no being may know the secrets of Aurioch. To this shall your
guile and craft be pledged.


E 2
I 1
E 1
