h47446
s 00038/00000/00000
d D 1.1 99/12/02 16:01:55 jmochel 2 1
cC
cK10285
cO-rw-rw-rw-
e
s 00000/00000/00000
d D 1.0 99/12/02 16:01:51 jmochel 1 0
c BitKeeper file G:/SpaceHybrid/worlds/ea/barbar.nr
cBjmochel@devilmountain.bedford.foliage.com|ChangeSet|19991202203126|52994|e2968a7f5cb68f67
cHdevilmountain.bedford.foliage.com
cK45011
cPworlds/ea/barbar.nr
cReb47867d5cb68f68
cZ-05:00
c______________________________________________________________________
e
u
U
f e 0
f x 33
t
T
I 2
The Barbarian Tribes Of Ea. 

The barbarian tribes of Ea are large. Despite the size many of 
these tribes they are relatively civilized. Some of the tribes 
are structured enough to support cities. The Val Tier and the 
White Wolf tribes each have cities. 

White Wolf: a matriarchal group of seven clans totalling 14000 
people. They live mainly in the great caves of luliendril in the 
temoroth region. They speak the sarin language. 

Black horse: a patriarchal set of three large clans( a total of 
8000 ).They roam the expanses of meremont and revere the horse. 
they speak sarin. 

Shaidahul: a nomadic group of desert walkers.they dominate the 
kasan desert region and compete with the orc tribes. they have an 
equality based society from which springs the catriders and the 
kedan or "water shaman". It is the shaidahul that collect the 
spicy exudate of the lion lizard and use it to produce both barut 
and nikitaa. They number in excess of 30,000. they speak 
caliphate. 

Grest: an ogre group of 100-400 tribes. they number in excess of 
15,000. they speak ogre. mostly found in the hills south of the 
dwarvish uplands and the deep desert.

Val'Tier: A seperate race, the Val'Tier live in the Val'Tier 
mountain region east of Herun. They are the most civilized of all 
barbarians. They are adept with Konjactl and Whipsword. they 
speak the language Basque.

Mai'La'Han'Aihan: (Kol) : 70,000 strong. these are the current 
riders of oceans and island of Ea.They live their lives on rafts. 
they come in to shore once in a great while to meet with other 
kol or to rebuild a raft. 


E 2
I 1
E 1
