h22604
s 00026/00000/00000
d D 1.1 99/12/02 16:01:58 jmochel 2 1
cC
cK50703
cO-rw-rw-rw-
e
s 00000/00000/00000
d D 1.0 99/12/02 16:01:55 jmochel 1 0
c BitKeeper file G:/SpaceHybrid/worlds/ea/blkstar.nr
cBjmochel@devilmountain.bedford.foliage.com|ChangeSet|19991202203126|52994|e2968a7f5cb68f67
cHdevilmountain.bedford.foliage.com
cK45011
cPworlds/ea/blkstar.nr
cReb47867c5cb68f68
cZ-05:00
c______________________________________________________________________
e
u
U
f e 0
f x 33
t
T
I 2
.so header.rof
.he //The Black Star Company//
.fo //Page #//
.in 9
.rm 71
.nf
.ce 1
Lord Anarka Val Din
.sp 2
Light Company           Shadow Company          Dark Company
.sp 1
Sgt. Lakash             Sgt. NehruNeht          Sgt. HashaKalatha
.sp 2
20 Squads Infantry      15 Squad Infantry       10 Squad Infantry
10 Squads Archer        05 Squad Archer         01 Squad Other
                        05 Squad Tracker/Scout
.sp 1  
.ce 1
Each Squad Consists of 5 men.
.sp 2
.fi
.NP
The Black Star Company is a highly paid and highly respected mercenary 
outfit. The are known both for their high discipline as garrison troops and
as scouts and spot infantry. 
 
E 2
I 1
E 1
