h44317
s 00026/00000/00000
d D 1.1 99/12/02 16:02:02 jmochel 2 1
cC
cK06934
cO-rw-rw-rw-
e
s 00000/00000/00000
d D 1.0 99/12/02 16:01:58 jmochel 1 0
c BitKeeper file G:/SpaceHybrid/worlds/ea/chargen.nr
cBjmochel@devilmountain.bedford.foliage.com|ChangeSet|19991202203126|52994|e2968a7f5cb68f67
cHdevilmountain.bedford.foliage.com
cK45012
cPworlds/ea/chargen.nr
cReb47867b5cb68f68
cZ-05:00
c______________________________________________________________________
e
u
U
f e 0
f x 33
t
T
I 2
Character Generation for EA

1	Roll as per Manual for points
2	Determine main statistics
3	Determine Secondary Statistics
4	Determine Race, Calculate effect of race on statistics
5	Determine Gender, Calculate effect on Statistics
6	Determine Aspect
7	Determine Culture -> Base language 
8	Determine Social Status ( See Seperate Tables )
9	Determine Birth ( See Racial tables )
10	Determine Height and weight from averages
11	Determine age
12	Determine Mind Gifts 
13	Determine Money
14	Determine Experience Points
15	Determine Skills
16	Determine History
	-	How Skills were recieved
	-	How Social status and birth affects them
	-	Take geneder and culture into account
	-	Take into account aspect and True Names
17	Determine religion
18	What does the character know of true names, other races, 
	and the rest of the outside world.

E 2
I 1
E 1
