h52420
s 00108/00000/00000
d D 1.1 99/12/02 16:02:39 jmochel 2 1
cC
cK14799
cO-rw-rw-rw-
e
s 00000/00000/00000
d D 1.0 99/12/02 16:02:36 jmochel 1 0
c BitKeeper file G:/SpaceHybrid/worlds/ea/descript.nr
cBjmochel@devilmountain.bedford.foliage.com|ChangeSet|19991202203126|52994|e2968a7f5cb68f67
cHdevilmountain.bedford.foliage.com
cK45015
cPworlds/ea/descript.nr
cReb4786715cb68f68
cZ-05:00
c______________________________________________________________________
e
u
U
f e 0
f x 33
t
T
I 2
The Book of Constructions

Being a compendium of the facts major and minor known about the
planet Ea.(AAA-Yaa) 
 
The Universe:  

     More correctly called the multiverse. There is a large
number of planes related to the plane of interest called the
prime material plane.  

The Solar system:

     The star is a single sun of the white dwarf form. There are
three moons in near circular orbits. None of the moons can
support life. The moons are Litaha,Yrtha,Yamen. 
 
The World of Ea:

     The world itself is a planet with G=1.2 times
that of Sol III. The planet has 60% water coverage with one
large continent and several large islands. The year is 400
days(24 hrs) long with 40 10 day weeks. There are 10 4 week
months.
 
Days:
     Religous    Grey Elven   Human    Dwarfish
 
1    sunday      Primus       Odeen    Guild
2    Ill day     Secundus     Dva      Argens
3    Heal Day    Teras        Tree     Mitras
4    Life day    Kwartus      Shet     Adama
5    Death Day   Pentast      Yach     Cupras
6    God Day     Sextus       Shest    Stibnas
7    Threat Day  Heptan       Sem      Ferrum
8    Peace Day   Octas        Vosem    Nickala
9    Growth Day  Quintus      Devat    Khol
10   Moon Day    Lunast       Desat    Lunan
 
Months:
 
#    Human       Elvish       HOLIDAYS
1    KAT         BEAST        Day  Holiday
2    HAWK        SIGHT         
3    WHALE       STRENGTH     075  Prophets day, Odins Birth
4    UNICORN     SAFETY       090  Spring'scoming
5    BEAR        WILL         123  All Hallowed Day
6    WOLF        CUNNING      154  Lycan's end
7    PEGASI      FREEDOM      231  Night's ending ( Dwarvish Elvish Pact)
8    GRIFFON     SCENT        200  Midsummers eve
9    RAT         FEAR         281  Harvest Day
10   SPHINX/OWL  WISDOM

.bp
Moons Cycles: 
     See Figure
 
Two Moon Eclipses:        Three moon Eclipses:
____________________________________________________________
Day 275 every 26 years     day 171 every 108 years
 
     1422                  781
     1448                  |
     1474                  1429
 
The Continent: 
     This is a fairly young planet. The mountains are very young
and fairly sharp. The crust is fairly well defined in its metal
bearing regions.  
     The south western area of the continent has many hot water
geysers of a fairly violent nature. Along with these geysers and
springs comes a wealth of mineral salts and heat based
ores(cinnabar and copper sulfide). There are some earthquakes
here though they are rare and of low damage potential. 
     To the north lies an area of some limited volcanic
activity. The Valtier ranges has several active volcanoes as
does Osterland,Temoroth,and the Kaylins. The mountains of Isig
have only residual activity of this sort. The southern Dwarvish
ranges are almost devoid of volcanism . 
     The Northern most areas beyond the Isig range and east are
without any real mineral wealth. Yet there are many coal and
water based gemstones(amber) to be found here. 
 
The Climates:
     The northern most area are artic tundra. The areas of
Osterland and Temoroth are similiar to Denmark and Finland.
Felice and Canias display a climate closer to the northern coast
of Ireland. The belt of land between Meremont and the Kaylins
are identical to the North American continent. The Shir has a
climate like that of the Pacific Northwest. 
     Below the Kaylins the clime warms considerably. The plains
are large semi-arid and windy. The San-Sir area is even drier
and warmer. Below the dry and Tough Dwarvish mountains the land
becomes a full fledged and vicious desert with only the western
coast having any respite from the high heats and dry Sirriccos
or Hershinas of the Kasan. 

The Wildlife:
     The powers of natural mana are strong and because of this
it is unlikely that any of the fantastical creatures of the land
will become extinct. Dragons and Their ilk are unlikely to be
pushed out by anything as puny as man. The area of the Kaylins
are a place where an armed dwarf walks warily.
     The woods of Elhayns deep, fully consecrated in 200-1443 ,
are a perfect refuge for many of the more scarce faery folk. 
     The plant life and woods of Ea are best covered elsewhere.
.bp

E 2
I 1
E 1
