h46222
s 00005/00000/00000
d D 1.1 99/12/02 16:02:46 jmochel 2 1
cC
cK09659
cO-rw-rw-rw-
e
s 00000/00000/00000
d D 1.0 99/12/02 16:02:43 jmochel 1 0
c BitKeeper file G:/SpaceHybrid/worlds/ea/elf.nr
cBjmochel@devilmountain.bedford.foliage.com|ChangeSet|19991202203126|52994|e2968a7f5cb68f67
cHdevilmountain.bedford.foliage.com
cK45016
cPworlds/ea/elf.nr
cReb47866f5cb68f68
cZ-05:00
c______________________________________________________________________
e
u
U
f e 0
f x 33
t
T
I 2
Eyes on elves 

Wood Elves - Vertical Slit
High Elves - Vertical Ovoid - rounded at end of Slit
Drow - All pupil. 
E 2
I 1
E 1
