h48454
s 00022/00000/00000
d D 1.1 99/12/02 16:02:57 jmochel 2 1
cC
cK11288
cO-rw-rw-rw-
e
s 00000/00000/00000
d D 1.0 99/12/02 16:02:53 jmochel 1 0
c BitKeeper file G:/SpaceHybrid/worlds/ea/header.nr
cBjmochel@devilmountain.bedford.foliage.com|ChangeSet|19991202203126|52994|e2968a7f5cb68f67
cHdevilmountain.bedford.foliage.com
cK45017
cPworlds/ea/header.nr
cReb47866c5cb68f68
cZ-05:00
c______________________________________________________________________
e
u
U
f e 0
f x 33
t
T
I 2
.pc C hex 0f .
.pc c hex 12 .
.pc I hex 1b 34 .
.pc i hex 1b 35 .
..
.wh hex 1b 32 .
.fr 2 hex 1b 33 12 .
..
.dm NP
.sp 1
.ne 2
.ti +5
.em
..
.dm IN
.br
.in $0
.em
..
.sc &
.tc ~
.ow 80
E 2
I 1
E 1
