h22371
s 00047/00000/00000
d D 1.1 99/12/02 16:03:21 jmochel 2 1
cC
cK51201
cO-rw-rw-rw-
e
s 00000/00000/00000
d D 1.0 99/12/02 16:03:18 jmochel 1 0
c BitKeeper file G:/SpaceHybrid/worlds/ea/lang.nr
cBjmochel@devilmountain.bedford.foliage.com|ChangeSet|19991202203126|52994|e2968a7f5cb68f67
cHdevilmountain.bedford.foliage.com
cK45020
cPworlds/ea/lang.nr
cReb4786655cb68f68
cZ-05:00
c______________________________________________________________________
e
u
U
f e 0
f x 33
t
T
I 2
	The Languages of EA

	Gray Elven or Niramaa
		This language is directly descended from TrueSpeech and is a
		quiet,tonal language. It is spoken in the areas around
		Allece,Canias,Felice,Culmaiea,& Leeward. 

	Caliphate
		A quick semispoken language with many clicking
		consonants. Spoken in the areas around the kaylin
		Mts.,The Leeward Cape, The Eastern of Culmaiea,and down
		along the coast south of Culmaiea. 

	Mantic
		Also known as old Karmadic. A low toned, solid language
		with little poetry involved in it. It is spoken by the
		humans of Isig, Oen and	some parts of Ymris. Most of
		the Northernmost lands use it except for Meremont. Also
		used by	the humans of the northern of dwarvish kingdoms.

	Sans 
		A seagoers language. Used by the Kol, some of the
		western islands and many of the southernmost tradertowns. 

	Osterole
		A most poetic language Spoken in Roke and most of the
		eastern islands.

	Kargan
		A singular language with few uses. Very gutteral in
		nature. Spoken in the plains below the Val-Tier Mts and
		in San-Sir. 

	Basque
		The language of the Val-Tier. 

	Hardic
		The language of the Mimbrate pennisula and surrounding
		environs. Definitely a polite and courteous language. 

	Aroyan
		The flowing part halfling speech of the overlook mountains. 

	Sarin
		The language of Osterland and Temeroth.            

 
E 2
I 1
E 1
