h53206
s 00092/00000/00000
d D 1.1 99/12/02 16:04:15 jmochel 2 1
cC
cK15978
cO-rw-rw-rw-
e
s 00000/00000/00000
d D 1.0 99/12/02 16:04:12 jmochel 1 0
c BitKeeper file G:/SpaceHybrid/worlds/ea/poison.nr
cBjmochel@devilmountain.bedford.foliage.com|ChangeSet|19991202203126|52994|e2968a7f5cb68f67
cHdevilmountain.bedford.foliage.com
cK45025
cPworlds/ea/poison.nr
cReb4787965cb68f68
cZ-05:00
c______________________________________________________________________
e
u
U
f e 0
f x 33
t
T
I 2
Name-Path-Type-Onset-Duration-Potency Loss-Damage-Description-Comment

Path
	Insinuative(IN)
		Insinuative poisons are those that require a break in
		the skin in order to enter the blood stream and take action.

	Contact(CO)
		Contact poisons are those that can be absorbed through
		the skin. Typically these poisons take longer to enter
		the system and take effect.

	Ingestive(IG)
		Ingested poisons are those that are taken into the body
		by food or drink. These are the most common and
		generally the most effective of all poisons.

	Airborne(AP)
		Airborne Powder poisons are those rare toxins that are
		taken into the body by being inhaled. There are only a
		few of these in existence.

	Gas(GS)
		Gas poisons are taken into the body by being inhaled.
		There are only a few of these in existence. Rarely are
		they carried in their natural state. Usually the
		materials needed to create them are carried and
		combined at the site of deployment.

    Special(SPC)
		Any of a variety of other paths that are truly out of
		the ordinary.

Type
   Death Dealing(DD)
	    Death Dealing poison require the victim to roll a saving
		throw. If that saving throw is failed then the user
		will die at the end of he duration of the poison's effect.

    Paralytic(P)
	    Paralytic poisons require a saving throw versus
		paralysation. If failed the character will be limited
		in action until the end of the poison's duration

    Damage(D)
	    Damage doing poisons are the most common. They require a
		saving throw against poison. If the save is failed the
		character will take damage as detailed by the fifth
		element in the poison designation. The damage will be
		taken once per each basic time element. As an example,
		if a poison has a duration of 10 rounds and a damage of
		1d6 then the character takes 1d6 of damage per round.

	Hallucinogenic(H)
	    Hallucination poisons are uncommon but often effective. If a save is made then the character is able to ignore the shades his made is throwing up on all sides of him. If he fails then his actions are slowed to half speed and he gets a minus in combat equa	      l to 1/2 the amount he missed the ST by.

	Sleeping(SL)
           Sleep poisons are fairly straight forward. A ST is made at the onset of the poison. If failed the character falls asleep. The character is entitled to another ST at halfway through the duration.

        Special(SPC)
            These are special effect poisons that have non-standard effects

    Onset Time
        As described in the Materials Designation

    Duration
        As described in the Materials Designation

    Potency Loss
        As described in the Materials Designation

    Damage
        First Character # of die of damage
        Second Character set = size of die of damage
        and then a mod
        i.e. 2d12+1 = 2-24+1

Insinuative Poisons Coats Per Dose
    Dart                    8
    Arrow                   4
    Dagger                  2
    Hand Axe                2
    Scimitar                1
    Spear                   1
    Pole Arm                1 Edge
    Short Sword             1 Edge
    Broadsword              1/2 Edge
    Bastard Sword           1/2 Edge
    Longsword               1/2 Edge
	T-sword                 1/3 Edge

Typically raw plant poisons are less effective and more subject to potency loss than poisons prepared from the plant.
E 2
I 1
E 1
