
UPDATE sc_system_names SET common = 'Alpheratz' WHERE hip = 677;
UPDATE sc_system_names SET common = 'Caph' WHERE hip = 746;
UPDATE sc_system_names SET common = 'Algenib' WHERE hip = 1067;
UPDATE sc_system_names SET common = 'Ankaa' WHERE hip = 2081;
UPDATE sc_system_names SET common = 'Shedir' WHERE hip = 3179;
UPDATE sc_system_names SET common = 'Diphda' WHERE hip = 3419;
UPDATE sc_system_names SET common = '96 G. Psc' WHERE hip = 3765;
UPDATE sc_system_names SET common = 'Van Maanens Star' WHERE hip = 3829;
UPDATE sc_system_names SET common = 'Mirach' WHERE hip = 5447;
UPDATE sc_system_names SET common = 'Achernar' WHERE hip = 7588;
UPDATE sc_system_names SET common = 'p Eridani' WHERE hip = 7751;
UPDATE sc_system_names SET common = 'Hamal' WHERE hip = 9884;
UPDATE sc_system_names SET common = 'Polaris' WHERE hip = 11767;
UPDATE sc_system_names SET common = '268 G. Cet' WHERE hip = 12114;
UPDATE sc_system_names SET common = 'Menkar' WHERE hip = 14135;
UPDATE sc_system_names SET common = 'Algol' WHERE hip = 14576;
UPDATE sc_system_names SET common = '82 G. Eri' WHERE hip = 15510;
UPDATE sc_system_names SET common = 'Mirphak' WHERE hip = 15863;
UPDATE sc_system_names SET common = 'Alcyone' WHERE hip = 17702;
UPDATE sc_system_names SET common = 'Aldebaran' WHERE hip = 21421;
UPDATE sc_system_names SET common = 'Kapteyns Star' WHERE hip = 24186;
UPDATE sc_system_names SET common = 'Rigel' WHERE hip = 24436;
UPDATE sc_system_names SET common = 'Capella' WHERE hip = 24608;
UPDATE sc_system_names SET common = 'Bellatrix' WHERE hip = 25336;
UPDATE sc_system_names SET common = 'Alnath' WHERE hip = 25428;
UPDATE sc_system_names SET common = 'Nihal' WHERE hip = 25606;
UPDATE sc_system_names SET common = 'Arneb' WHERE hip = 25985;
UPDATE sc_system_names SET common = 'Alnilam' WHERE hip = 26311;
UPDATE sc_system_names SET common = 'Alnitak' WHERE hip = 26727;
UPDATE sc_system_names SET common = 'Saiph' WHERE hip = 27366;
UPDATE sc_system_names SET common = 'Betelgeuse' WHERE hip = 27989;
UPDATE sc_system_names SET common = 'Canopus' WHERE hip = 30438;
UPDATE sc_system_names SET common = 'Alhena' WHERE hip = 31681;
UPDATE sc_system_names SET common = 'Sirius' WHERE hip = 32349;
UPDATE sc_system_names SET common = 'Adhara' WHERE hip = 33579;
UPDATE sc_system_names SET common = 'Luytens Star' WHERE hip = 36208;
UPDATE sc_system_names SET common = 'Castor' WHERE hip = 36850;
UPDATE sc_system_names SET common = 'Procyon' WHERE hip = 37279;
UPDATE sc_system_names SET common = 'Pollux' WHERE hip = 37826;
UPDATE sc_system_names SET common = 'Alphard' WHERE hip = 46390;
UPDATE sc_system_names SET common = 'Regulus' WHERE hip = 49669;
UPDATE sc_system_names SET common = 'Groombridge 1618' WHERE hip = 49908;
UPDATE sc_system_names SET common = 'Algieba' WHERE hip = 50583;
UPDATE sc_system_names SET common = 'Merak' WHERE hip = 53910;
UPDATE sc_system_names SET common = 'Lalande 21185' WHERE hip = 54035;
UPDATE sc_system_names SET common = 'Dubhe' WHERE hip = 54061;
UPDATE sc_system_names SET common = 'Denebola' WHERE hip = 57632;
UPDATE sc_system_names SET common = 'Groombridge 1830' WHERE hip = 57939;
UPDATE sc_system_names SET common = 'Phad' WHERE hip = 58001;
UPDATE sc_system_names SET common = 'Acrux' WHERE hip = 60718;
UPDATE sc_system_names SET common = 'Alioth' WHERE hip = 62956;
UPDATE sc_system_names SET common = 'Vindemiatrix' WHERE hip = 63608;
UPDATE sc_system_names SET common = 'Mizar' WHERE hip = 65378;
UPDATE sc_system_names SET common = 'Spica' WHERE hip = 65474;
UPDATE sc_system_names SET common = 'Alkaid' WHERE hip = 67301;
UPDATE sc_system_names SET common = 'Hadar' WHERE hip = 68702;
UPDATE sc_system_names SET common = 'Arcturus' WHERE hip = 69673;
UPDATE sc_system_names SET common = 'Proxima Centauri' WHERE hip = 70890;
UPDATE sc_system_names SET common = 'Rigel Kentaurus B' WHERE hip = 71681;
UPDATE sc_system_names SET common = 'Rigel Kentaurus A' WHERE hip = 71683;
UPDATE sc_system_names SET common = 'Izar' WHERE hip = 72105;
UPDATE sc_system_names SET common = 'Kochab' WHERE hip = 72607;
UPDATE sc_system_names SET common = '33 G. Lib' WHERE hip = 73184;
UPDATE sc_system_names SET common = 'Alphekka' WHERE hip = 76267;
UPDATE sc_system_names SET common = 'Unukalhai' WHERE hip = 77070;
UPDATE sc_system_names SET common = '+025' WHERE hip = 77442;
UPDATE sc_system_names SET common = 'Antares' WHERE hip = 80763;
UPDATE sc_system_names SET common = 'Rasalgethi' WHERE hip = 84345;
UPDATE sc_system_names SET common = 'Shaula' WHERE hip = 85927;
UPDATE sc_system_names SET common = 'Rasalhague' WHERE hip = 86032;
UPDATE sc_system_names SET common = 'Etamin' WHERE hip = 87833;
UPDATE sc_system_names SET common = 'Barnards Star' WHERE hip = 87937;
UPDATE sc_system_names SET common = 'Kaus Australis' WHERE hip = 90185;
UPDATE sc_system_names SET common = 'Vega' WHERE hip = 91262;
UPDATE sc_system_names SET common = 'Nunki' WHERE hip = 92855;
UPDATE sc_system_names SET common = 'Tarazed' WHERE hip = 97278;
UPDATE sc_system_names SET common = 'Altair' WHERE hip = 97649;
UPDATE sc_system_names SET common = 'Deneb' WHERE hip = 102098;
UPDATE sc_system_names SET common = 'Lacaille 8760' WHERE hip = 105090;
UPDATE sc_system_names SET common = 'Alderamin' WHERE hip = 105199;
UPDATE sc_system_names SET common = 'Enif' WHERE hip = 107315;
UPDATE sc_system_names SET common = 'Alnair' WHERE hip = 109268;
UPDATE sc_system_names SET common = '-020' WHERE hip = 110478;
UPDATE sc_system_names SET common = 'Kruger 60' WHERE hip = 110893;
UPDATE sc_system_names SET common = '+011' WHERE hip = 113131;
UPDATE sc_system_names SET common = 'Fomalhaut' WHERE hip = 113368;
UPDATE sc_system_names SET common = 'Scheat' WHERE hip = 113881;
UPDATE sc_system_names SET common = 'Markab' WHERE hip = 113963;
UPDATE sc_system_names SET common = 'Lacaille 9352' WHERE hip = 114046;
