h25942
s 00093/00000/00000
d D 1.1 99/12/02 16:02:17 jmochel 2 1
cC
cK54329
cO-rw-rw-rw-
e
s 00000/00000/00000
d D 1.0 99/12/02 16:02:14 jmochel 1 0
c BitKeeper file G:/SpaceHybrid/worlds/ea/combat.nr
cBjmochel@devilmountain.bedford.foliage.com|ChangeSet|19991202203126|52994|e2968a7f5cb68f67
cHdevilmountain.bedford.foliage.com
cK45013
cPworlds/ea/combat.nr
cReb4786775cb68f68
cZ-05:00
c______________________________________________________________________
e
u
U
f e 0
f x 33
t
T
I 2
.HE //Combat Clarifications and Extenmsions for DQ//
.NH 1
Combat Terminology
The following has been changed or Clarified
.IP PULSE 10
A five second increment of game time
.IP ACTION 10
An Action is the movement and /or physical activity
that can be performed during ones IV. Single Actions start 
on a persons IV and go to his next IV. Some actions may 
take Multiple IVs.
.IP IV 10
The period of time during which a character may act. Many
characters  may have multiple IVs per pulse. Each new IV is
determined by subtracting 15 from the previous IV. IVs are
designated by the terms Primary, Secondary,  and Tertiary.
Actions performed during the Primary IV ( The first IV) are 
performed at the full base chance. Actions performed during the
Secondary IV  are done with 1/2 the base chance (for pass
actions this is a DF of 3.5). Actions performed during the
Tertiary IV are at 1/4 base chance ( Pass Actions are DF 1.5).  
.bp
.NH 1
Combat Sequence
.DS
1.  Initiative is determined for all unengaged figures and
    engaged figues.

2.  Actions are performed in the order of their IVs.
.DE
.PP
Actions rated in terms of number of IVs they take to perform.   
.ST "IVs per Action"
Action                                                  IVs
Search for trap in specific place                       8
Quick Search of 10' x 10' area                          6
Sound Wall                                              4
Search 100 square foot wall for Concealed objects       40
Force Lock                                              6
Spike Door                                              4
Take off Standard Backpack                              10
Take off SIdepack                                       2
Light Torch                                             45
Light Lantern                                           55
Mount/Dismount Horse                                    2
.SE
.NH 1
Special Combat Actions
.IP Iajutsu 15
A skill roll is made and a bonus is added on to
the primary IV. The bonus does not add in to all the following
IVs.
.IP Disarm 15
One Half of the defender's Weapon's Base Chance is
subtracted from the strike chance. If the strike is successful
the defender rolls a Manual Dex save at DF=1.
.IP 
If the disarm is being attempted with a missile or thrown 
weapon the full base chance of the weapon is subtracted.
.IP Blocking 15
Blocking is the act of giving up a chance to attack and instead 
, attempting to actively block the attackers weapon from
reaching you. Upon each attack, the defender rolls a block
using the attackers SN as a modifier against his roll. (ie.
Ralph attacks Leroy and hits by 37. Then leroy has to roll his
normal strike chance less 37%.) If a successfull block is made
then damage is rolled for both sides. Any damage that the
attacker inflicts over and above that done by the defender,
gets through. If the attack is a grievous strike then a normal
block would reduce it to just an endurance strike, a endurance 
rolled block would reduce the damage to fatigue, and a grievous
effect block would nullify the damage. 
.IP 
Ralph attacks Leroy with an endurance hit for 7 points. Leroy
blocks all the damage and gets it bounced up to just fatigue.
Leroys strikes Ralph for an Endurance shot but Ralph can only
block out most of the damage , the rest of the damage goes
against Endurance.
.IP Parrying 15
Parrying is the act of defending one's self from attack using 
a weapon to aid in avoiding damage. There is no attempt to directly 
oppose your opponents weapon with your own. 
.IP
Parrying is done as the book states but the minus is based on
defense + dexterity + 4% * Rnk in weapon. 
.IP
A successful parry resulting in a roll of 8+ leads to the next 
IV occurring as if it were the next higher class. A roll of 3 or less
leads to the next IV occuring as if it were the next lower class.
.IP Evasion 15
For now, as per book


E 2
I 1
E 1
