h00900
s 00071/00000/00000
d D 1.1 99/12/02 16:02:25 jmochel 2 1
cC
cK29016
cO-rw-rw-rw-
e
s 00000/00000/00000
d D 1.0 99/12/02 16:02:21 jmochel 1 0
c BitKeeper file G:/SpaceHybrid/worlds/ea/culture.nr
cBjmochel@devilmountain.bedford.foliage.com|ChangeSet|19991202203126|52994|e2968a7f5cb68f67
cHdevilmountain.bedford.foliage.com
cK45014
cPworlds/ea/culture.nr
cReb4786755cb68f68
cZ-05:00
c______________________________________________________________________
e
u
U
f e 0
f x 33
t
T
I 2
                                                                          Page 1
C:\DND\CULTURE.SL                                            13-Aug-1989 3:03 pm


  > Physical Resources
      . Noticeable Raw Materials
      . Hidden Assets
      . Neighboring Assets

  . Technology
  . Subsistence Patterns
  . Values and Kinship
  > Language
      . Language Tree
      . Mapping
      . Dialects
      . Literacy
      . Writing Forms
      . Sounds
      . Vocabulary and Grammer

  . Religion,Myths,and History
  . Cosmology and Dieties
  > Tradition
      . Wedding
      . Bedding
      . Birthing
      . Battle
      . Other

  > Clergy
      . Rites and Rituals
      . Religious Norms

  . Institutions
  > Art, Architecture, and Symbolism
      > Symbolism
          . Common Motifs
          . Significant Numbers

      . Art
      . Architecture

  > Politics
      > Leadership
          . Stated
          . Actual

      . Class Controls
      . Judicial Structure
      > Legal Code
          . Ownership of Goods
          . Land
          . Male and Female Roles
          . Church and State
          > Death
              . By Suicide
              . By Anothers Hand
              . In Self Defense
                                                                          Page 2
C:\DND\CULTURE.SL                                            13-Aug-1989 3:03 pm


  > Military
      . Standing
      . Command
      . Routine
      . Arms
      . Outfitting
      . Theory

E 2
I 1
E 1
