h60417
s 00361/00000/00000
d D 1.1 99/12/02 16:02:53 jmochel 2 1
cC
cK23004
cO-rw-rw-rw-
e
s 00000/00000/00000
d D 1.0 99/12/02 16:02:50 jmochel 1 0
c BitKeeper file G:/SpaceHybrid/worlds/ea/grayelf.nr
cBjmochel@devilmountain.bedford.foliage.com|ChangeSet|19991202203126|52994|e2968a7f5cb68f67
cHdevilmountain.bedford.foliage.com
cK45017
cPworlds/ea/grayelf.nr
cReb47866d5cb68f68
cZ-05:00
c______________________________________________________________________
e
u
U
f e 0
f x 33
t
T
I 2
	Cultural Outline - Gray Elves

	Description

The Gray Elven culture consists of a limited number of Gray
Elves with a fairly consistent and uniform set of social
structures. The range in number from 10,000 in the city state of
Culmaiea to as low as 4,000 each in the northern cities of
Felice and Canias. They, of all the elven races, prefer cities
and towers of marble. 

The race of Gray Elves are exiles or stranded travellers, even
the Gray Elves themselves are unsure. The Niramaa, as the Gray
Elves name themselves, were led to this plane long ago by
Korrelian and still await the time when they may go back from
whence they came. 


Average HT: 6'2" Average WT: 165 lbs. 
Hair : Blond to Platinum Blond. 
Eyes : Violet to Silver eyes with Inwardly stressed hexagonal pupil
Skin : Fair to purest white skin 

+2 MA -2 EN +1 APP
0 Longsword 
0 Longbow 
All Niramaa are psionic. 

Require 4-6 hours of sleep. 
Heart Beat 100/min 
Gestation Period 13 months 
With 1-2 children per lifetime 
 

Wounds taken from cold Iron take 2 * as long to heal or 2 * as
much healing. Iron shackles remove all chances of performing
magic and increase the cost of psionics by a factor of two. In
addition, all Niramaa avoid eating raw red meat as well as oily
fishes because of the Iron content. 

Physical Resources

Perhaps the greatest resource the gray elven race has is
arrogance. The next greatest would be their magery and
leadership. They are often asked to serve as arbitrators in
disputes. 

Noticeable Raw Materials

The Gray Elven cities of Culmaeia, Felice, and Canias are
seemingly well stocked with power. Each city has a form of "Mage
Battery" that any of their race may tap for spells and psionic
magery.  

Subsistence Patterns

Despite their great power, for most things, the Gray Elves are
dependent on tribute brought to them in exchange for protection
and aid given to the various peoples of the area. 


Values and Kinship

As they are exiles the Niramaa tend to be very protective of
their own . Their is no greater or more hideous crime than that
of kinslaying. The Gray Elves are arranged into clans and
families. Competition between clans is limited to non-lethal
combat.  

Descent is determined the child for the clan of the parent of
the same sex as the child. Thus a child whose father is of the
Elenair clan and whose mother is of the Istari clan would be
considered to be of the Elenair if it was male and of the Istari
if female. 

Age is considered to be very important in determing precedence
in social situations. Second comes power and then skill.  

The Major Clans of the Gray Elves
------------------------------------------------------------ 
Rhyslian                Dove                    Healers
Alda'an(An'alda)        White Birch             Government
Istari                  Mapletree with Pentacle Mages
Selebdin                Silver Coronet          Smiths
Thalionser              Silver Gauntlet         Warriors 

The Minor Clans of the Gray Elves
------------------------------------------------------------ 
Tharwin                 Cross Current or spray  Scholars 
Elenair                 Single Star             Judges
Faeglin                 Spirit Gleam            
Galenseem               Green Hand              Rangers
Formenkith              Rising Mist


Language 

The language spoken by the gray elves is listed in the standard
language tree and is called Gray Elven. There are no dialects
of Gray Elven and literacy is almost universal. 

The written language is very much the Quenyan runes of Tolkien
fame. The sounds of Gray Elven are a cross between spanish and
gaelic. 

Vocabulary and Grammer

When using spoken Gray Elven the omission of a formal prefix
indicates great intimacy. 

Standard forms of address;
------------------------------------------------------------ 
clan head or great Mage  :                             Vai'Dom 
                                                       Vai'Doma
older male               :                             Dom 
older female             :                             Doma
Peer male                :                             Tai'Dom
     female              :                             Tai'Doma 
younger male             :                             Lai'Dom 
      female             :                             Lai'Doma 

Other Vocabulary
------------------------------------------------------------ 
Great                                                   Vai 
Evil                                                    Dabla
Light                                                   Laem
Dark                                                    Drom
Elf                                                     Niramaa
Greeting                                                Aveela
Justice                                                 Maelaam
Thank You                                               Graen
Please                                                  Kaelees


Religion,Myths,and History

Major Historical Figures
------------------------------------------------------------ 

Vai Dom Maerlin Istari: Wizard of the third
============================================================
Instrumental in fighting the creatures that "bridged" during the
cataclysm. died 1325 

Gaerlin Faerilor Saernim Alda'an : Leader of a thousand
============================================================
Negotiator of the Pact of final Peace died 1209 

Dom Lederlaen Selebdin : Forger of Glamdring
============================================================ 
died 506 

Tovanaer Thrylan An'Alda: Saviour of the prophet
============================================================ 
died 900 

Vai Doma Kysraleen Elenair : Poet and Statesman
============================================================ 
Greatest of the Niramaa epic storytellers. Wrote both the "Chronicles
of the Cataclysm" and "Human's Lament" died 1045 

Dom Kisraemin Formenkith: Mage
============================================================ 
Former Archmage of Roke. died 1335 

Tura Aur Faeglin: Mage Druid
============================================================ 
Founder of Maleindrill. Responsible for the deaths of 164 elves in
269. Caught and sentenced to the "non death" in 275. "Died" in 331.
Reborn in 1140. Enfeebled in 1444. 


Cosmology and Dieties

The Niramaa live in a fairly smug position. They know that the
gods pay personal attention to their race - how else could they
have ended up on this plane ? As a result they tend to be fairly
religious. They love Korellian and honor Ptah.  

Tradition

Wedding and Bedding 

Weddings are often a formal recognition of a lifebond betwen two
Gray Elves. An exchange of bracelets is often observed as well
as isolation during the initial "bonding period". There is no
nudity taboo and Gray Elves are not particularly sensitive about
such things among themselves. By the same token such exposure
to others of non Niramaa is close to unthinkable. Niramaa thus
rarely mate with other races such as humans, though it has been
known to happen. Usually the offspring of such a birthing are
loved by their family ( even the Gray Elven clan of the parent
if it is of that clan ) and barely tolerated by the Niramaa of
other clans. 

Gray Elves cannot be made pregnant against their will, indeed it
is difficult for them to become pregnant when they wish to.
Bithings are usually difficult and rarely can an Gray Elven
women tolerate more than two such experiences. Yet, despite
this, there are really any deaths in childbirth. 

Battle

Most of he Gray Elven attitudes towards combat are shaped by
their status as exiles. They tend to view their own people as
non-expendable and all of their attacks tend to be of a nature
designed to optimize their gains. There is rarely a situation
that justifies a "suicide" attack. Single magery duels are the
most common form of combat seen by Niramaa. 

Rites and Ritual

The most important celebrations to a Gray Elf are those relating
to his day of birth and his gaining of psionics. A Gray Elven
birth is a signal for six days of feasting as well as gift
giving. In addition, clergy of both faiths are asked to give the
child a true name and a use name. Usually a near relative of
importance to the parents is asked to decide between the two
sets of names. This favored figure, called the "choice" mother
or father is the only one other than the child and the clergy to
know the child's true name. 

Institutions and Clergy

Gray Elven culture is very religious and their worship of Ptah and
Korellian is noticable in almost all walks of life. Each clan keeps
its own day for Koreelian and their own day for Ptah. 

Almost all magical rituals invoke Ptah and almost all jurisprudence
invokes Korellian. 

The clergy of Korellian is recruited in a manner similiar to
that used to get members of the clergy for human clerics. It is
often the case that a child will be called to serve Korellian
for a short period of time and then released to pursue other
interests. 

The clergy of Ptah are, without exception, drawn from the mages
and scholars among the Gray Elves. Clerics of Ptah gain no
clerical spells, instead they gain a large number of additional
Magic user or illusionist spells. 

Technology

Niramaa have a highly developed sense of precision that they
apply to Magery and crafts. Unfortunately they seem to be more
interested in the abstract than the physical. This effectively
means that while they may create some new spells they rarely
apply that creativity to the workshop. Note the major ward of
protection around the city of Culmaiea. 

Art, Architecture, and Symbolism 

Gray Elves tend to favor marble and granite as building
materials. Usually these are shaped by a mage and inset with
some type of mosaic. The pictures are often enhanced by the use
of magery. 

Most of the artwork is based on some interpretation of magery
though there are some animal pictures. Gray Elves are very
fascinated by cats, a creature that is not native to their
plane. 

Clothes and Dress

Niramaa tend to favor simple but ornate clothing with trousers
for both genders as well as a blouse and either full or half
capes. Dresses are worn only during formal when no duties press
upon the person. Robes are sometimes worn as a statement of
position and power. Generally all of these will be plain or
decorated with intricated colored patterns along the trim.
Jewelry also tends to be simple - cunningly wrought silver
chains or interwoven platinum rings.


Politics and Warfare

The Niramaa culture is based on a true democracy. All mature
members of the race vote. Such voting is done by a group of
psionics who poll each person and add the totals up. They are
then truth read when they give the totals to a magistrate. 

There is no Gray Elven leader. Each city waits upon the arrival
of the chosen, who will lead them back to their homeland. Each
city has its own regent who is selected from a group of
individuals noted for their scholarship. The cit regents handle
only the day to day problems of rule. Any drastically new
problem has to be handled by a voting call. 

Military matters are handled by individuals most familiar with
the area or problem in question. There is almost always a
current leader of a thousand (see below) available to handle
full scale maneuvers. 

There are no real classes within Gray Elven culture. There is a
servant group but it is filled mostly from apprentices of
other races and outsiders that are being trained in some craft.
There are a few individuals who work for the Gray Elves in
order to observe them. While there is no class structure, the
concept of precedence is very important to the Niramaa. So
important is this concept that only the person who convened a
meeting or conference can ask that it be interrupted or
altered. 

Things that are considered crimes by the Gray Elves are quite
simple: 

Attacks on a Niramaa's Body or Spirit. 
Reckless Endangerment with magery. 
Attacking the shields around the city of Culmaeia. 
Stealing - usually dealt with by the target 

Crimes against a Church ( even a outsider's ) is given over to the
church in question. 

The legal structure is fairly simple as well as fairly
effective. Anyone who is accused by a Gray Elf may be brought
before the court. The court will usually consist of a single
"law holder" who will conduct initial inquiries into the crime
under a truth read. If there is reason to believe that there is
a chance of a crime having been committed then the case
proceeds to a full court. A full court consists of 7 mages or
scholars to suggest a line of questioning, a truth reader, and a
law holder to protect the individual being questioned from
embarrassing lines of inquiry. In the case of an outsider being
accused, a court officer familiar with his race is provided. 

Foreign Relations are handled by the regent of the city
involved. Currently there is only one culture that has major
problems with the Niramaa and that is the Drow. 


Military Structure

The Gray Elven military is very much a puzzle for most military
historians. There is almost no set chain of command to insure
that something gets done. A military briefing consists of a
psionic explanation of what needs to be done, along with some
guidelines, and the troop is sent off to do what they can. 

In situations requiring more than 10 warriors the gray elves do
have a formalised structure. Each one in ten is chosen as a
leader of ten. There are also leaders of 100 and a leader of
1000. These are usually chosen for their familiarity with an
area rather than military experience. 

In general they have no real routines but guards are almost
always posted and their normal care about iron in their food
takes care of most poisoning attempts. 

As been noted before they are all well trained in Longbow and
Longsword. Almost all of their longswords are of the bronze or
mithril steel type. In addition almost all are equipped with
spear as well as light shield. All arrows are bronze or silver.
In addition all are equipped with a canteen of wine and some
waybread. 

The general military tactics consist of using stealth and speed
to get what must be done, done. The greatest aid the gray elves
have is their psionic communications. 

E 2
I 1
E 1
