h04482
s 00024/00000/00000
d D 1.1 99/12/02 16:04:37 jmochel 2 1
cC
cK32796
cO-rw-rw-rw-
e
s 00000/00000/00000
d D 1.0 99/12/02 16:04:34 jmochel 1 0
c BitKeeper file G:/SpaceHybrid/worlds/ea/skcost.nr
cBjmochel@devilmountain.bedford.foliage.com|ChangeSet|19991202203126|52994|e2968a7f5cb68f67
cHdevilmountain.bedford.foliage.com
cK45027
cPworlds/ea/skcost.nr
cReb4787905cb68f68
cZ-05:00
c______________________________________________________________________
e
u
U
f e 0
f x 33
t
T
I 2
.so header.rof
.he //The Costs of Skills by Type//
.fo //Page #//
.in 5
.rm 71
.nf
.ce 1
Type of Skill
.sp 3
            Simple Skill        Craft       Art
        
Rank    
0           200                 250         300
1           75                  100         125
2           125                 200         300
3           300                 500         850
4           550                 950         1400
5           850                 1450        2200
6           1350                2050        3400
7           1700                2800        4200
8           2250                3600        5300
9           2900                6300        6800
10          3500                8000        9500
11+         6500                9000        1050
E 2
I 1
E 1
