h47774
s 00038/00000/00000
d D 1.1 99/12/02 16:04:52 jmochel 2 1
cC
cK10100
cO-rw-rw-rw-
e
s 00000/00000/00000
d D 1.0 99/12/02 16:04:48 jmochel 1 0
c BitKeeper file G:/SpaceHybrid/worlds/ea/strpgear.nr
cBjmochel@devilmountain.bedford.foliage.com|ChangeSet|19991202203126|52994|e2968a7f5cb68f67
cHdevilmountain.bedford.foliage.com
cK45029
cPworlds/ea/strpgear.nr
cReb47878c5cb68f68
cZ-05:00
c______________________________________________________________________
e
u
U
f e 0
f x 33
t
T
I 2
                                                                               
         The Geneology of StripGear Hammerwielder: Dwarven Molester            
                                                                               
                Balthoris the Bastard - 1st Wielder and Creator of Thor        
                Titian Headache       - 2nd Wielder of Thor                    
                Poundin Anvil Wyvern Hunter                                    
                Kickin Ass            - 3rd Wielder of Thor                    
                                                                               
                                                                               
       Antiquity -----------------------------------------------               
                                                                               
                 Balan Giant Twister          Galan the worthless              
                         ³                          ³                          
                         ³                          ³                          
                         ³                          ³                          
                                                                               
                 Ganlinmor the Arm            Koolin lizard Kicker             
                 Lierst the Heedless     ÚÄÄÄ Kliand Bum Tosser                
                         ³               ³           ³                         
                         ³               ³           ³                         
                         ³               ³           ³                         
                 Castus high roller <ÄÄÄÄÙ ÚÄ>Mathian Skirt Lifter             
                         ³                 ³         ³                         
                         ³                 ³         ³                         
                         ÀÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÙ         ³                         
                                              Toulin The Wise                  
                                                     ³                         
                                                     ³                         
                 Goulin Orc Punter    <ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÙ                         
                        ³                                                      
                        ³                                                      
                        ³                                                      
                        ³                                                      
                        ÀÄÄÄÄÄÄÄÄÄÄÄÄ> Saral Sea Finder                        
                                             ³                                 
                                             ³                                 
                Kroftlis       <ÄÄÄÄÄÄÄÄÄÄÄÄÄÙ                                 
          StripGear Hammerwielder                                              
E 2
I 1
E 1
