h63446
s 00124/00000/00000
d D 1.1 99/12/02 16:05:13 jmochel 2 1
cC
cK25949
cO-rw-rw-rw-
e
s 00000/00000/00000
d D 1.0 99/12/02 16:05:10 jmochel 1 0
c BitKeeper file G:/SpaceHybrid/worlds/ea/val-tier.nr
cBjmochel@devilmountain.bedford.foliage.com|ChangeSet|19991202203126|52994|e2968a7f5cb68f67
cHdevilmountain.bedford.foliage.com
cK45031
cPworlds/ea/val-tier.nr
cReb4787865cb68f68
cZ-05:00
c______________________________________________________________________
e
u
U
f e 0
f x 33
t
T
I 2
Description
    All of a Val-Tier's (Val-Tee-Air) physical statistics are generated using the procedure in Unearthed Arcana for Barbarians. The average Val-Tier is 8' (+ or - 6") Weight 270 lbs. They are a fairly dark skinned race with bleach blonde hair. 7% of all women     are platinum blonde (y-linked recessive) They have a fairly high resistance to alcohol and are well adapted for great heights. 

Physical Resources
    Noticeable Raw Materials
        The mountains of Val-Tier are relatively poor in mineral wealth and rich in plant and animal wealth

    Hidden Assets
    Neighboring Assets

Technology
    The technological level of the Val-Tier is fairly primitive among most of the cultures of EA.
    They have metal workers capable of producing excellent steel but they are dependent on outside sources for Iron and Coal. 
    They possess simple fire starters and oil lamps.

Subsistence Patterns
    The Val-Tier are a somewhat unique barbarian culture. They are both hunter/gatherers and farmers. They perform a simple form of terrace agriculture for a number of root stocks. They also cultivate various nut tress. 
    They hunt and take only the culls among the game of the area. Typically, they hunt deer, mountain sheep, bear, rabbit, boar, and sometimes buffallo on the plains north of the range.

Values and Kinship
    The Val-Tier are an ancestor worship based culture. The believe that one's ancestors are the only spirits hat influence a man or womans fate. 
    They prize bravery, thrift, and cleverness. As a result they consider fighters and thieves to be equally honorable traits. They dislike assassins, not because of their techniques , but because they take money in order to kill.  
    They are a magic phobic culture. Shamans are respected (Somewhat) . MoonSingers and Dancers are respected. Druids are tolerated. Clerics are disliked and most mages can arouse intense hatred with little difficulty.
    They have few racial intolerences and a very few have been known to take grey elves as mates.(twice in the last two thousand years) 
    Despite their love of theives the culture is very polite. A man may leave even the most valuable belongings in a clan house and be assured of finding it there when he returns. Any who have eaten meat and drink with the tribe may claim "shared meat" sanctu    ary for a day and a night. 

Language
    Language Tree
        They have their own language called Basque 

    Mapping
    Literacy
        Few of the Val-Tier can use the written version of the Val-Tier Those that can are tribal record keepers, shamans or wise women.

    Writing Forms
        A simple runic phonetic language

    Sounds
        Kul Hon Val San Han Jor Tay Hor Har Thol

    Vocabulary and Grammer
        Keehannah - Wise Women
        Chalket - Sister
        Tonhol - Brother
        Shiva - Warrior/Scout/Thief
        Shek - Scum
        Monhor - Kin Slaughterer

Myths, and History
    The Val-Tier have a simple method of keeping 

Cosmology and Dieties
Tradition
    Wedding
    Bedding
    Birthing
    Battle
    Other

Clergy
    Rites and Rituals
    Religious Norms

Institutions 
Art, Architecture, and Symbolism
    Symbolism 
        Common Motifs
        Significant Numbers

    Art
    Architecture

Politics
    Leadership
        Stated
        Actual

    Class Controls
    Judicial Structure
    Legal Code
        Ownership of Goods
        Land
        Male and Female Roles
        Church and State
        Death
            By Suicide
            By Anothers Hand
            In Self Defense 

Military
    Standing
    Command
    Routine
    Arms
    Outfitting
    Theory


The Val-Tier( Vale-Tee-yair ) nation is a matriarchal variation upon
the Seneca long house nation. It is a total matriarchy with deep ancestral
ties. ( Never pick on a Val-Tier's mother) 

Each clan is ruled by the Keehannah or wise mother. She is almost sacred 
and to offer harm of any type to her is a death sentence. Within her
hall: the long house, there is no fighting. It is considered an honor to
be allowed to wear weapons into the long house. At the Keehannah's side is
a shaman or Hounnah. The shaman is of mixed status for though he does not
fight, sing or theive it is said that he may talk with impunity to the
tribe's dead. (He can) The Back bone of the tribe is its scouts or
Shiva's . Armed with the 6' Val-Tier whip sword and the 7'bows of the
mountains they are an efficient hunting group in peace and a deadly army
in time of war. The weapons unique to the Valtier are the whip sword,the
great bow, and the Konjactal. 

Whipsword: require 6' SF 5 2-12/1-6

Greatbow: Warbow of the Val-Tier does a d8/d8   

The Konjactal: A three bladed folding throwing knife with the follow-
ing properties:

1. May only be thrown
2. On a miss of 5 or less (outside) it will return to the user.
3. damage is a d3+2/d3+1  ranges: 1/2/3 
E 2
I 1
E 1
