h43671
s 00009/00000/00000
d D 1.1 99/12/02 16:05:28 jmochel 2 1
cC
cK06103
cO-rw-rw-rw-
e
s 00000/00000/00000
d D 1.0 99/12/02 16:05:24 jmochel 1 0
c BitKeeper file G:/SpaceHybrid/worlds/ea/welfclan.nr
cBjmochel@devilmountain.bedford.foliage.com|ChangeSet|19991202203126|52994|e2968a7f5cb68f67
cHdevilmountain.bedford.foliage.com
cK45032
cPworlds/ea/welfclan.nr
cReb4787825cb68f68
cZ-05:00
c______________________________________________________________________
e
u
U
f e 0
f x 33
t
T
I 2
MERCHANT TABLE

% ROLL		TYPE		MODIFIER

01-40		POOR		-20
41-65		FAIR		-10
66-80		GOOD		+0
81-95		WEALTHY 	+5
96-00		VERY
E 2
I 1
E 1
