RV00000002
DL09
CO49
LN00
WM01
DD03
PF0080
PF0166
PF020
PF030
PF040
PF056
PF061
PF070
PF081
PF091
PF101
PF11Designation of Healing Materials
PF12
PF131
PF14
PF150
PF162
PF1732767
PF1815
PF194
PF203
PF210
PF221
PF231
PF2432767
PF251
HD01O
Name-Preparation-Type-Onset-Duration-Potency Loss-Damage Healed-Description-Comment
HD02O
Name
HD03O
Usually the most common name for the medicine
HD02O
Preparation
HD03O
Poultice(PL)
HD04O
A poultice is a paste used upon the exterior of the body
HD03O
Decoction(DC)
HD04O
A decoction is a brew of water or spirits and the material in question. It is taken internally.
HD03O
Tincture(TN)
HD04O
A tincture is a solution made by steeping the material in spirits or filtering spirits through the material in question. 
HD03O
Airborne Powder(AP)
HD04O
An airborne powder is usually a finely crushed powder inhaled through the nose or mouth.. 
HD03O
Gas(GS)
HD04O
Exceedingly rare method of applying medications
HD03O
Injection(IN)
HD04O
Usually administered on the edge of a knife or in a sharply pointed tube.
HD03O
Raw(RW)
HD02O
Type
HD03O
Fatigue Healing(FH)
HD03O
Hits Healing(HH)
HD03O
Anti Infection(AI)
HD03O
Sedatives(SD)
HD03O
Fever Remedy(FR)
HD03O
Pain Killer(PK)
HD03O
Poison Antidotes(AN)
HD03O
Various(VAR)
HD02O
Onset Time 
HD03O
As described in Materials Designation
HD02O
Duration
HD03O
As described in Materials Designation
HD02O
Potency Loss
HD03ONC
As described in Materials Designation
HD02O
Damage Healed 
HD03O
As described in Poison Designation
HD02O
Description
HD03O
A simple description of how it looks, feels, smells, and other details involving its impact on the senses.
HD02O
Comment
HD03O
A comment is typically additional notes about the material that cannot be covered in the description
