RV00000002
DL03
CO25
LN00
WM01
DD05
PF0080
PF0166
PF020
PF030
PF040
PF056
PF061
PF070
PF081
PF091
PF101
PF11MoonSingers, MoonsDancers, and Human Shades
PF12
PF131
PF14
PF151
PF162
PF1732767
PF1815
PF193
PF202
PF211
PF221
PF231
PF2432767
PF251
HD01ONC
History
HD02O
Distant
HD03O
In the time period following the raising of Roke, there came into existence a small kingdom that came to be known as Kevar. Kevar was ruled by a family that was admired by most of its people because, if for no other reason, each ruler was trained and educated by a shade of his or her predecessor.
HD03O
The people of Kevar were gifted in that the land was rich for growing and hunting as well as having a good amount of various mineral deposits. The Kevarans came to be known as gifted sailors and traders with a strong wanderlust.
HD03O
In the third century after the establishment of this kingdom Kevar came to be at odds with a nearby kingdom called Hiramar. The land of Hiramar was held in the grip of a theocracy of a faith called O-Gon. The rulers of this kingdom viewed Kevar with hunger, for its lands were rich in a way that Hiramar could never be.
HD03O
The religion of the O-Gon was a brutal one, requiring complete obedience and obeisence from the people of the culture. Yet, this was not necessarily a source of discontent, for the people of the Hiramar were secure in the strong belief that they and theirs were the only people strong enough to rule over the islands. They were a harsh and arrogant people , ruled over by an even harsher clergy: known as the Ten-O-Gon.
HD03O
For nearly 50 years battles were waged between the two island kingdoms. In the year, 1134, during the highest (noon) hour of the third day of the month of the Hawk the Ten-O-Gon struck and killed most of the royal family of Kevar. The survivors of the city of LysJal were hunted and the guard scattered. Most succeeded in making it to the mainland and became wanderers. Others settled down to a roving existence and lived on to become what is now known as the "Rafters" or Kol.
HD03O
Those in exile on the mainland maintained a roving existence rather than settle in any area where they would come to owe alliegience to any specific ruler. As the exile entered its second decade those who had survived gathered together , first in small groups and then in larger groups. The leaders, often surviving members of the royal guard or of the Royal heraldmages, met and discussed a common problem.  Their people were losing their culture and their old skills.  If they were ever to take back their land these skills needs must be preserved. It was then that the last named ruler of Kevar came forward and presented all of his people with the technique of calling up a shade.
HD03O
The shade/instructors/teachers/companions, known as Tulathin, saved a large portion of the skills and teachings that were the heritage of the Kevarans. They were little talked about, even among those that possess them. It is quite likely that they were little understood even by those select few that could pass on the knowledge.
HD03O
The Ten-O-Gon held the island with no obvious lessening in the strength of their hold over the centuries. As these ages passed the people of Kevar began to blend in with the cultures of the mainland. Despite this there are always a few of their ancestors traits that cling to them. Usually a love of bright clothing and gay music and dance. Those that retained the skills of their ancestors came to be known as MoonSingers or MoonDancers.
HD02O
Near
HD03O
In the 1100s came the second cataclysm and with it the greatest days for the Ten-O-Gon. They were free to hunt the surviving remnants of the Kevar culture with relative freedom. Their skills in deception and illusion aided them greatly in hunting their enemies. Only the rapidly rising strength of the Tulathin trained Singers and Dancers allowed any Kevarans to escape.
HD03O
The Dancers and Singers of the time were sorely pressed and barely held when their traditional allies the druids were defeated. They reached their lowest numbers with the death of the Archdruid Ardren Forest-Heart in 1132. There were but 200 Singers on the continent at the close of the cataclysm.  Gradually they developed new strengths and found new allies in the church of Sif and the church of Uller. As the cataclysm faded into memory, they became instrumental in the founding of Covenant and in the pacification of the Kaylin ranges.
HD03O
With their skills in divination and healing they came to be welcome in most towns and villages on the mainland. They developed a reputation as skilled midwives and healers. As if by common concensus, the Dancers and Singers have avoided any displays of martial skills of any type.
HD03O
As time went on the Singers gained greatly in numbers. They are known of in almost all towns and villages though they avoid the larger cities and keeps. They are viewed with suspicion by dwellers of the larger towns because they have become confused with the gypsy like Kol or their cousins of the plains, the Kolak.
HD03O
The Ten-O-Gon continued their persecution of the descendants of the Kevaran though they became less effective as the Druids again rose in power. Any man or woman of the Ten-O-Gon would welcome the chance to kill any of Kevaran blood that still live.
HD03O
In the year 1443 came the slaughter of many of the Ten-O-Gon in the plains around The Stones of Tiberius. With this defeat and the loss of their leader, Keeshin the Ten-O-Gon have been badly hurt. And for the first time there has been news that has originated in the Ten-O-Gon ruled lands of Kevar.
HD03O
There are still some surviving Kevarans on Kevar but it is believed that their long fight against the Ten-O-Gon have left them a worn and battered group. It is said that the old skills have been turned to use as pure survival weapons.
HD01O
Politics
HD02O
The Lines of Singers and Dancers
HD03O
General
HD04O
Each of the major lines of MoonSingers and MoonDancers was established by the teachings of a particular survivor of the Heralds or Royal Guard of the last ruler of Kevar. In each case the line has developed a certain flavor to its skills and techniques.
HD04O
Students of the various schools are protective of the "Secrets" of the schools but not to the point of jepordizing the chance of the "Returning"
HD03O
The Line of Yos'Talin
HD04O
Thar Yos'Talin was the last Master Herald of his time and he has fostered one of the strongest lines of MoonSingers though there are no Dancers of his line. His teachings were conservative and this is reflected in their very stern view regarding the altering of tradition. Because of the ease with which they can summon their shade tutor, they gain a +10% to their chance to the Summon Shade skill.
HD03O
The Line of Nor'Jordan the Blind
HD04O
Nor'Jordan is one of the most interesting lines of MoonSingers because there has always been a great deal of question regarding the fact that his teachings best benefit female Singers. All woman who study within this discipline gain a +10% to all healing effects and Chances.
HD03O
The Line of Lin'Hathan
HD04O
The line of Lin'Hathan is descended from one of the most dazzling figures of Kevaran history. Both healer and Royal Guardsman, Lin'Hathan is credited with a large number of ballads and songs. This line treats the summoning of a shade as a ritual and is unable to do so without at least 10 rounds of concentration. But they are quite skilled at the art of MoonSinging and gain a +5% in all MoonSinging activities.
HD03O
The Line of Kliander Oathkeeper
HD04O
Kliander Oathkeeper is Considered to be a very controversial figure among the singers. Kliander was one of the few non-Kevaran Heralds that served the King at the time of Kevar's fall. He taught a very pragmatic method of summoning shades and was skilled at sorting myth from fact in much of Kevaran mageries. Followers of the Oathkeeper gain a Detect Lie spell and a TruthSee spell.
HD03O
The Line of Sol'Dan the Hound
HD04O
Atham Sol'Dan was a beast trainer in the Royal Guard and discovered early on in his exile that his affinity for animals extended to shapechanging teachings. Any who study his style gain a +5% to all changing abilities.
HD03O
The Line of Hal'Kani
HD04O
Hal'Kani was a Royal Herald whose skill in outguessing the Ten-O-Gon ( Later discovered to be premonition based ) saved many of her people from death. Any who follow her eachings gain a +10% to all divinations.
HD03O
The Line of Tal'Rus
HD04O
As Sol'Dan, Tal'Rus discovered a strong affinity to shapechanging. His real talents lay in the darker areas of Hunting and Slaying. It is Tal'Rus who fathered the line of "Human Shades" that haunt the hills of Kevar.
HD01O
Descriptions
HD02O
MoonSingers
HD03O
Singers are those of the Kevaran mage-skilled who have chosen to focus their abilities through the use of an instrument or their voice. They tend to be skilled in the spellcasting arts and less skilled in the martial arts.  MoonSingers are able to see as an elf in the night, without any color definition. All Singers must take one non-weapon proficiency in Singing. Any additional proficiencies add 5% to the MoonSinging bonuses.
HD03O
The MoonSingers, when using any instrument at all, tend to favor the use of either the drum or tambor. In weaponry the tend to favor daggers, scimitars, staves and bolas. All moonSingers favor the Kevaran language as well as their "Native" tongue.
HD03O
In general, female MoonSingers outnumber male Singers approximately 5:1 . By the same token the ratio reverses itself in regards to MoonDancers.
HD03O
Statistics
HD04O
A MoonSinger needs must have the following stats:
HD04O
Str: 12 Dex: 15 Con: 12 Int: 15 Wis: 14
HD03O
Combat Tables
HD04O
They attack and save as thieves of the same level
HD03O
Experience
HD04O
Experience Points      Level    HD  PROF   Title
HD04O

HD04O
        0 -     2,500      1       2d6  2/4  1st Novice
HD04O
    2,501 -     5,000      2       1d5  -    2nd Novice
HD04O
    5,001 -     9,500      3       1d5  1    3rd Novice        
HD04O
    9,501 -    16,250      4       1d5  -    4th Novice
HD04O
   16,251 -    25,000      5       1d5  1    1st Initiate
HD04O
   25,001 -    43,000      6       1d5  -    2nd Initiate
HD04O
   43,001 -    75,000      7       1d5  1    3rd Initiate
HD04O
   75,001 -   112,500      8       1d5  -    4th Initiate
HD04O
  112,501 -   150,000      9       1d5  1    1st MoonSinger
HD04O
  150,001 -   250,000      10      1d5  -    2nd MoonSinger
HD04O
  250,001 -   375,000      11      1d2  1    3rd MoonSinger
HD04O
  375,001 -   937,500      12      1d2  -    4th MoonSinger
HD04O
  937,001 - 1,800,000      13      1d2  1    Master Singer
HD04O
1,800,001 - 3,600,000      14      1d2  -    Arch Master
HD03O
Spell Level Table
HD04O
                      Spell Levels
HD04O

HD04O
       LVL       1    2    3    4    5    6    7
HD04O

HD04O
       1         2    -    -    -    -    -    -
HD04O
       2         2    1    -    -    -    -    -
HD04O
       3         3    2    -    -    -    -    -
HD04O
       4         3    2    1    -    -    -    -
HD04O
       5         4    2    1    -    -    -    -
HD04O
       6         4    3    2    1    -    -    -
HD04O
       7         5    3    2    1    -    -    -         
HD04O
       8         5    3    2    2    -    -    -    
HD04O
       9         6    4    3    2    1    -    -
HD04O
       10        6    4    3    3    1    -    -
HD04O
       11        7    5    3    3    2    1    -
HD04O
       12        7    5    4    4    2    1    1
HD04O
       13        8    6    4    4    3    2    1
HD04O
       14        8    6    5    5    3    2    2
HD02O
MoonDancers
HD03O
Dancers are similiar to the MoonSingers except that they have choosen to focus all of their skills through dance.  They tend to be less skilled in the casting arts. All Dancers must take a proficiency in Dance. They have the same sight modifiers as Singers.
HD03O
They also tend to favor the same languages and instruments as the Singer. Their taste in weapons leans toward scimitars and short swords as well as throwing knives and Jo sticks.
HD03O
Statistics
HD04O
A MoonDancer needs the following stats:
HD04O
Str: 12 Dex: 15 Con: 14 Int: 15  Wis: 12
HD03O
Combat Tables
HD04O
They attack and save as thieves of the same level
HD03O
Experience 
HD04O
Experience Points      Level    HD  PROF   Title
HD04O

HD04O
        0 -     2,500      1       2d6  4/2  1st Novice
HD04O
    2,501 -     5,000      2       2-5  -    2nd Novice
HD04O
    5,001 -     9,500      3       2-5  1    3rd Novice        
HD04O
    9,501 -    16,250      4       2-5  -    4th Novice
HD04O
   16,251 -    25,000      5       2-5  1    1st Initiate
HD04O
   25,001 -    43,000      6       2-5  -    2nd Initiate
HD04O
   43,001 -    75,000      7       2-5  1    3rd Initiate
HD04O
   75,001 -   112,500      8       2-5  -    4th Initiate
HD04O
  112,501 -   150,000      9       2-5  1    1st MoonDancer
HD04O
  150,001 -   250,000      10      2-5  -    2nd MoonDancer
HD04O
  250,001 -   375,000      11      1d3  1    3rd MoonDancer
HD04O
  375,001 -   937,500      12      1d3  -    4th MoonDancer
HD04O
  937,001 - 1,800,000      13      1d3  1    Master Singer
HD04O
1,800,001 - 3,600,000      14      1d3  -    Arch Master
HD03O
Spell Level Table
HD04O
Spell Levels
HD04O

HD04O
       LVL       1    2    3    4    5    6    7
HD04O

HD04O
       1         1    -    -    -    -    -    -
HD04O
       2         2    -    -    -    -    -    -
HD04O
       3         2    1    -    -    -    -    -
HD04O
       4         3    1    -    -    -    -    -
HD04O
       5         3    2    1    -    -    -    -
HD04O
       6         3    2    1    -    -    -    -
HD04O
       7         4    2    2    1    -    -    -         
HD04O
       8         4    3    2    1    -    -    -    
HD04O
       9         4    3    2    2    -    -    -
HD04O
       10        5    3    3    2    1    -    -
HD04O
       11        5    4    3    2    1    -    -
HD04O
       12        5    4    3    3    1    1    -
HD04O
       13        6    4    4    3    2    1    1
HD04O
       14        6    5    4    3    2    2    1
HD02O
Human Shades
HD03O
Humans Shades are the Assassin/Hunter/Mages of the Kevaran back hills. They see in the Dark as a singer and gain a +5% on all Hide in Shadow,Climb Walls, Walk Silently, and Tracking rolls.
HD03O
Tulathin gain a +Lvl/2 on all saves against poison.
HD03O
They tend to speak only the Kevaran tongue and are skilled in the use of Blowgun, daggers, and leaded rope. They rarely deal with instruments.
HD03O
Statistics
HD04O
A Kevar "Human Shade" needs the following stats:
HD04O
Str: 13 Dex: 15 Con: 16 Int: 13 Wis: 12
HD03O
Combat Tables
HD04O
They attack and save as thieves of the same level
HD03O
Experience Points
HD04O
  Experience Points      Level    HD  PROF   Title
HD04O

HD04O
        0 -     2,500      1       2d7  6/1  1st Novice
HD04O
    2,501 -     5,000      2       1d6  -    2nd Novice
HD04O
    5,001 -     9,500      3       1d6  1    3rd Novice
HD04O
    9,501 -    16,250      4       1d6  -    4th Novice
HD04O
   16,251 -    25,000      5       1d6  1    1st Initiate
HD04O
   25,001 -    43,000      6       1d6  -    2nd Initiate
HD04O
   43,001 -    75,000      7       1d6  1    3rd Initiate
HD04O
   75,001 -   112,500      8       1d6  -    4th Initiate
HD04O
  112,501 -   150,000      9       1d6  1    1st MoonSinger
HD04O
  150,001 -   250,000      10      1d6  -    2nd MoonSinger
HD04O
  250,001 -   375,000      11      1d4  1    3rd MoonSinger
HD04O
  375,001 -   937,500      12      1d4  -    4th MoonSinger
HD04O
  937,001 - 1,800,000      13      1d4  1    Master Singer
HD04O
1,800,001 - 3,600,000      14      1d4  -    Arch Master
HD03O
Spell Level Table
HD04O
                      Spell Levels
HD04O

HD04O
       LVL       1    2    3    4    5    6    7
HD04O

HD04O
       1         -    -    -    -    -    -    -
HD04O
       2         1    -    -    -    -    -    -
HD04O
       3         1    -    -    -    -    -    -
HD04O
       4         1    1    -    -    -    -    -
HD04O
       5         2    1    -    -    -    -    -
HD04O
       6         2    1    1    -    -    -    -
HD04O
       7         2    2    1    -    -    -    -         
HD04O
       8         3    2    1    1    -    -    -    
HD04O
       9         3    2    2    1    -    -    -
HD04O
       10        3    3    2    1    -    -    -
HD04O
       11        4    3    2    2    1    -    -
HD04O
       12        4    3    3    2    1    -    -
HD04O
       13        4    4    3    2    1    1    -
HD04O
       14        4    4    3    3    2    1    -
HD01O
Skills
HD02O
General 
HD03O
Both MoonSingers and MoonDancers have access to three types of mageries: Healing, Divination, and Changing.
HD03O
The base chance for each of these skills to be used is equal to 4 * Wisdom of the character. These chances are modified by the phase of the moon that governs the specific type of magic.
HD03O
Healing is governed by the moon Litaha. Usually MoonSingers and Dancers are better at performing the more subtle healings of disease,Poison, and broken bones than at repairing various wound trauma.
HD03O
Divination is governed by the moon Yrtha. Usually the best auguries are those that regard events farther in the future than tomorrow or the next day.
HD03O
Changing is governed by the moon Yamen. These changes are exclusively aligned toward self-shapechanging.
HD02O
Effects of the moon.  
HD03O
For each area of magery there is a moon that governs the chance of casting a given spell
HD03O
Summoning Shade
HD04O
Tulathin or "Shades" are companion/teachers that are either constructs made to simulate a specific personality or the actual soul of an individual who is able to teach a Singer or Dancer the skills necessary to his craft.
HD04O
The Base chance to summon a shade is 5 * Wisdom. In addition there are modifiers for the line that one has been trained in as well as the moon cycle, etc.
HD04O

HD04O
*1 Any Moon at Full                   +20%
HD04O
*2 Each Round of Setup                +1%
HD04O
*3 Dancing/Singing                    +Wisdom%
HD04O
*4 Night                              +5%
HD04O

HD04O
Usually the shade is first summoned when the student is apprenticed. The shade is usually from the same line of study as the student is being trained in and is of a level no greater than that of the Singer/Dancer's wisdom. It is always of the same gender as the character and is of the same class as that of the student.
HD04O

HD04O
*1 Only for the one peak night.
HD04O
*2 For a maximum of wisdom in rounds.
HD04O
*3 Based on the class of the character.
HD04O
*4 Based on actual sundown.
HD01O
Spell Lists
