h44745
s 00037/00000/00000
d D 1.1 99/12/02 16:01:47 jmochel 2 1
cC
cK07094
cO-rw-rw-rw-
e
s 00000/00000/00000
d D 1.0 99/12/02 16:01:43 jmochel 1 0
c BitKeeper file G:/SpaceHybrid/worlds/ea/assguild.nr
cBjmochel@devilmountain.bedford.foliage.com|ChangeSet|19991202203126|52994|e2968a7f5cb68f67
cHdevilmountain.bedford.foliage.com
cK45010
cPworlds/ea/assguild.nr
cReb47867f5cb68f68
cZ-05:00
c______________________________________________________________________
e
u
U
f e 0
f x 33
t
T
I 2
Assasins Guilds of Ea 

Each guild has a unique power and economic structure. But in each
case the main function of the guild is to protect its members and 
their jobs. 

Usually there is one very strong rule: No non member shall run on our
turf. Any outsider who wishes to "work" on guild turf must either
clear the specific job with the guild ( usually at a high fee),  Join
the guild ( Not an easy proposition ), or try and perform the the job
and trust to luck.  

Locating other guilds

Most guilds charge a small ( 1-2 sp ) fee to view a guild listing of
other guilds. This listing usually describes most guilds and methods
of contacting them. Once contact has been made the guild usually
requires a "tithe" of all work done in the area.(10-30%) Someone who
risks the exposure of the guild or a guild member in someway can
expect to be blacklisted( usually > year) , framed, hunted, or
killed.  

It is possible that a higher level assassin will be able to issue
challenge to a guild for a game of "wit and weapon" in order to win 
the right to work in that guild for one year.

Most guilds have several sets of special symbols of special symbols
and some form of sign or whistle language. 

As an assassin gains in level he may gain some special abilities as
per the guild he works for.  

Most guilds will mantain a professional library and one or two
scribes. Usage of the library is usually free to a member. There are
often safe houses for members to sleep in. 

There are a number of guilds specific to various cities and areas.
E 2
I 1
E 1
