h56215
s 00051/00000/00000
d D 1.1 99/12/02 16:02:14 jmochel 2 1
cC
cK18645
cO-rw-rw-rw-
e
s 00000/00000/00000
d D 1.0 99/12/02 16:02:10 jmochel 1 0
c BitKeeper file G:/SpaceHybrid/worlds/ea/colleges.nr
cBjmochel@devilmountain.bedford.foliage.com|ChangeSet|19991202203126|52994|e2968a7f5cb68f67
cHdevilmountain.bedford.foliage.com
cK45013
cPworlds/ea/colleges.nr
cReb4786785cb68f68
cZ-05:00
c______________________________________________________________________
e
u
U
f e 0
f x 33
t
T
I 2
.he
.PP
The magical colleges of Tanah are in many respects unlike those of
standard DQ in that they are not exclusive in principle. They are 
simply a collection of spells and rituals based on a similiar set
of principles that can be used to form a magical school.
.PP
There are a number of basic principles that each of the colleges is 
based on. 
.PP
The Principles are as follows:
.IP The Elements
An element can be summoned or shaped by will
Opposite elements striving against each other provides handles for will
.IP The Essences
Names are keys to essence
Runes are physical embodiments of names
Patterns reflect essence
.IP The Entities
Will can dominate essence
.PP
The colleges that currently exist are:
.IP The Elements
Fire, Air, Water, Earth, Light, Dark
Shadow, Starlight
.IP The Essence
Naming, Rune, Shaping
.IP Entities
Greater Summmoning, Lesser Summoning
.PP
All of these basic items : Essence, Will, and the Elements are subject to 
a series of basic types of actions.
.IP Summoning
Summoning brings an already existent principle from another place via
already existent paths of travel
.IP Conjouring
Conjouring brings an already existent principle from another place via 
a direct gate.
.IP Concentrating
Takes already existing principle in the immediate area and brings it
into closer proximity with other, like principles.
.IP Dispersing
Takes already existing principle in the immediate area and causes it
to disperse.
.IP Transmute
Exchanges an existing principle for a like amount of another principle. 
.IP Shaping
Alters the external form of the principle. 
.IP Binding
Causes a tie to form between one principle and another.

E 2
I 1
E 1
