h65006
s 00061/00000/00000
d D 1.1 99/12/02 16:03:04 jmochel 2 1
cC
cK27365
cO-rw-rw-rw-
e
s 00000/00000/00000
d D 1.0 99/12/02 16:03:00 jmochel 1 0
c BitKeeper file G:/SpaceHybrid/worlds/ea/heraldry.nr
cBjmochel@devilmountain.bedford.foliage.com|ChangeSet|19991202203126|52994|e2968a7f5cb68f67
cHdevilmountain.bedford.foliage.com
cK45018
cPworlds/ea/heraldry.nr
cReb47866a5cb68f68
cZ-05:00
c______________________________________________________________________
e
u
U
f e 0
f x 33
t
T
I 2
	Heraldry of Ea

    FIELDS

	The Colours:
		Azure (blue)
		Scarlet (red)
		Purpure (purple)
		Sable (black)
		Verdant (green)
		Amber (yellow)

	The Metals:
		Argent (silver)
		Auric  (gold)
		Cupric (copper)

	The Furs:
		Pard ( gold w/ black spots )
		Ja'Pard ( black w/ white spots )
		Na'Pard ( white w/black spots )

	CHARGES

	Animals:
		Wolf	Eagle		Pard		Cat			Bear
		Boar	Weasel		Dragon		Lizard		Centaur
		Chimera	Basilisk	Cockatrice	Badger		Beaver
		Buffalo Bull		Crab		Crocadile	Dolphin 
		Eel		Goat		Griffon 	Harpy		Horse
		Stag	Jackal		Jaguar		Ki-	Rin		Lion	
		Naga	Owl			Pegasi		Woodsdrake	Ram	
		Ray		Rhino		Scorpion	Sea 		Horse	
		Sphinx	Unicorn 	Will-O-Wisp	Wolverine	Wyvern
		Pheonix

	 Items:
		Annulet 	Sword		Spear		Hammer		Axe		
		Baton		Gauntlet	Staff		Helm		Arrow	
		Bow			Crosses 	Bends		Bars		Chevron 
		Torch		Eye			Runes		Dagger		Flowers 
		Belt		Scroll		Mask		Quill		Chain	
		Circlet 	Goblet		Bell		Chessman	Instrument	
		Arrowheads	Sickle		Gem			Tree		Mistletoe
		Waterfall	Stone		Chisel		Banner		Lantern 
		Tower		Wheel		Crown

	Forms:
			Affronted - Full face
			Accosted - Side by Side
			Dexter, Sinister
			Chief,Fess,Base
			Addorsed - Back to Back
			Rampant,Resting,Engarde
			Availed - Side View






E 2
I 1
E 1
