h13880
s 00078/00000/00000
d D 1.1 99/12/02 16:03:53 jmochel 2 1
cC
cK42164
cO-rw-rw-rw-
e
s 00000/00000/00000
d D 1.0 99/12/02 16:03:50 jmochel 1 0
c BitKeeper file G:/SpaceHybrid/worlds/ea/monast.nr
cBjmochel@devilmountain.bedford.foliage.com|ChangeSet|19991202203126|52994|e2968a7f5cb68f67
cHdevilmountain.bedford.foliage.com
cK45023
cPworlds/ea/monast.nr
cReb47879c5cb68f68
cZ-05:00
c______________________________________________________________________
e
u
U
f e 0
f x 33
t
T
I 2

     MONASTERIES OF EA

	 Dawn's Break - North east corner of Isig mountains.
			Brother hood of Tempus 150 monks

	 Circle Home - In the city of Circles. Sister hood/ brother
		       hood of 70 monks. Primarily worship the
		       prophet.

	 Wind Sail Hall - In Amory. 407 monks in the Cloister of the
			  Prophet.

	 KulDama - Gray Elven monastary of Ptah in Canias 29
			   monks/ 07 sisters.

	 Wyvern Slash - Human monastery of the prophet. Established by
			Kerkajamen's 3rd incarnation. 49 monks

	 Sun's Sight -





















































E




E 2
I 1
E 1
