h02899
s 00041/00000/00000
d D 1.1 99/12/02 16:04:19 jmochel 2 1
cC
cK30995
cO-rw-rw-rw-
e
s 00000/00000/00000
d D 1.0 99/12/02 16:04:15 jmochel 1 0
c BitKeeper file G:/SpaceHybrid/worlds/ea/powergp.nr
cBjmochel@devilmountain.bedford.foliage.com|ChangeSet|19991202203126|52994|e2968a7f5cb68f67
cHdevilmountain.bedford.foliage.com
cK45025
cPworlds/ea/powergp.nr
cReb4787955cb68f68
cZ-05:00
c______________________________________________________________________
e
u
U
f e 0
f x 33
t
T
I 2
.nj
.nf
.in 5
.rm 78
.he  //^B MAGES GUILDS AND OTHER GROUPS OF MANA NATURE ^b //

BROTHERS OF TEMPUS

CLERICS

DARK BROTHERHOOD OF THE WOODS:"TEN-NO-GON"-WLKERS OF THE PATH

DROW OF THE SILVER LIVES

DRUIDS

GHOST RIDER- "SULAMAIN"

GIBBS GROUP

HIGHER CIRCLE OF THE MIMBRE KNIGHTS

IGA NINJA OF THE ISLAND EYODO

KARITHEEN - MAGE KILLERS

KEEDAN- WATER BRINGERS OF THE KASAN

MAGES

MASTERS OF ROKE

MOONSINGERS

NECROMANCIS

PROTECTORATE

SKINTURNERS

SUMMONERS OF "THE VOICES"
E 2
I 1
E 1
