h10707
s 00036/00000/00000
d D 1.1 99/12/02 16:04:56 jmochel 2 1
cC
cK38937
cO-rw-rw-rw-
e
s 00000/00000/00000
d D 1.0 99/12/02 16:04:52 jmochel 1 0
c BitKeeper file G:/SpaceHybrid/worlds/ea/styles.nr
cBjmochel@devilmountain.bedford.foliage.com|ChangeSet|19991202203126|52994|e2968a7f5cb68f67
cHdevilmountain.bedford.foliage.com
cK45029
cPworlds/ea/styles.nr
cReb47878b5cb68f68
cZ-05:00
c______________________________________________________________________
e
u
U
f e 0
f x 33
t
T
I 2


                           MARTIAL ARTS STYLES OF EA

         LARATH NO TOKEN        WIND ON HIGH
         ------------------------------------------------------------
         staff and jumps and throws



         WINAN NOTH             WHIRLING SILENCE
         ------------------------------------------------------------
         INC ATTACKS, QUIET,  KICKS




         KI NOSH KOVA           SHOUT INTO MIND
         ------------------------------------------------------------
                      KIAI,STRONG PUNCHES


         PIRAMON SETA           PHEONIX POISED
         ------------------------------------------------------------
         HYPNOTISM,MEDITATION


         KORE                   ALWAYS CENTERED
         ------------------------------------------------------------







E 2
I 1
E 1
