h60683
s 00052/00000/00000
d D 1.1 99/12/02 16:05:21 jmochel 2 1
cC
cK23303
cO-rw-rw-rw-
e
s 00000/00000/00000
d D 1.0 99/12/02 16:05:17 jmochel 1 0
c BitKeeper file G:/SpaceHybrid/worlds/ea/weather.nr
cBjmochel@devilmountain.bedford.foliage.com|ChangeSet|19991202203126|52994|e2968a7f5cb68f67
cHdevilmountain.bedford.foliage.com
cK45032
cPworlds/ea/weather.nr
cReb4787845cb68f68
cZ-05:00
c______________________________________________________________________
e
u
U
f e 0
f x 33
t
T
I 2
                                                                          Page 1
C:\DND\WEATHER.SL                                            13-Aug-1989 3:01 pm


  > Locales             Wind        Prec        Temp
      . Hot             +00         +200        +250
      . Warm            +00         +100        +125
      . Temperate       +00         +00         +00
      . Cool            +00         +00         -140
      . Cold            +00         +00         -240
      .

  > Month               Wind        Prec        Temp
      . Cat             +00         +50         -200
      . Hawk            +10         +75         -100
      . Whale           +10         +25         -50
      . Unicorn         +00         +00         +00
      . Bear            -10         -25         +25
      . Wolf            -20         -25         +50
      . Pegasi          -05         +00         +00
      . Griffon         +10         +10         -10
      . Rat             +25         +30         -80
      . Sphinx          +10         +40         -100
      .

  > Land Formations     Wind        Prec        Temp
      > Mtns
          . Young       +100        +100        -75
          . Old         +75         +50         -75
          . Steppe      +50         +25         -55
          . Mesa        +25         -20         +00

      > Lowlands
          . Hills       +00         +25         -20
          . Valleys     +00         +10         +00
          . Plains      +10         +00         +00

      > Wet Lands
          . Swamp       -30         +25         -10
          . Marsh       -35         +15         -10
          . Bog         -10         +00         -25

      > Waterlines
          . River Edge  +20         +10         -15
          . Lake Edge   +25         +15         -25
          . Sea Coast   +35         +35         -35

      > Water
          . River       +20         +15         -05
          . Lake        +30         +00         -10
          . Sea         +50         +00         -50

E 2
I 1
E 1
