RV00000002
DL05
CO26
LN00
WM01
DD05
PF0080
PF0166
PF020
PF030
PF040
PF056
PF061
PF070
PF081
PF091
PF101
PF11Designation of Materials used in healing and other areas
PF12
PF131
PF14
PF150
PF162
PF1732767
PF1815
PF194
PF203
PF210
PF221
PF231
PF2432767
PF251
HD01O
Name-Type-Availability-Habitat-Potency Loss-Usage-Description-Comment
HD02O
Name
HD03O
Typically the most common name is used
HD02O
Type
HD03O
Typically the character designating type of material is followed by a phrase in parentheses which gives more information. i.e. V(Tree) or M(Ore:Iron)
HD03O
Animal(A)
HD03O
Vegetable(V)
HD03O
Mineral(M)
HD03O
Other(O)
HD02O
Availability
HD03O
Very Common(VC)
HD03O
Common(C)
HD03O
Uncommon(UC)
HD03O
Rare(R)
HD03O
Very Rare(VR)
HD03O
Special(SPC)
HD02O
Habitat
HD03O
Frozen Waste(FRW)
HD03O
Tundra(TUN)
HD03O
Waste(WST)
HD03O
Rough(RGH)
HD03O
Plains(PLN)
HD03O
Fields(FLD)
HD03O
Heavy Woods(HWD)
HD03O
Light Woods(LWD)
HD03O
Wetlands(WTL)
HD03O
Sea Shore(SSH)
HD03O
Jungle(JNG)
HD03O
Caverns(CAV)
HD03O
Special(SPC)
HD02O
Potency Loss
HD03O
Potency loss is the amount of effectiveness loss per some period of time. It usually applies to any non-stabilized medicine, poison or magical usage of the material in question
HD03O
Time is described by the following abbreviations
HD04O
Seconds(s)
HD04O
Minutes(m)
HD04O
Hours(h)
HD04O
Days(d)
HD04O
Weeks(w)
HD04ONC
Months(mo)
HD04O
Years(y)
HD03O
Thus a 2 percent decay per every 3 days is designated 2%/3d
HD02O
Usage
HD03O
Food(FD)
HD03O
Poison(PO)
HD03O
Healing(HL)
HD03O
Magic(MG)
HD03O
Wood(WD)
HD03O
Dye(DY)
HD03O
Alchemical(AL)
HD03O
Special(SPC)
HD02O
Description
HD03O
A delineation of how the materials impacts upon our senses
HD02O
Comment 
HD03O
Other neat stuff not covered in the description
