RV00000002
DL14
CO24
LN00
WM01
DD06
PF0080
PF0166
PF020
PF030
PF040
PF056
PF061
PF070
PF081
PF091
PF101
PF11Designation of Poisons
PF12
PF131
PF14
PF150
PF162
PF1732767
PF1815
PF194
PF203
PF210
PF221
PF231
PF2432767
PF251
HD01O
Name-Path-Type-Onset-Duration-Potency Loss-Damage-Description-Comment
HD02O
Path
HD03O
Insinuative(IN)
HD04O
Insinuative poisons are those that require a break in the skin in order to enter the blood stream and take action.
HD03O
Contact(CO)
HD04O
Contact poisons are those that can be absorbed through the skin. Typically these poisons take longer to enter the system and take effect.
HD03O
Ingestive(IG)
HD04O
Ingested poisons are those that are taken into the body by food or drink. These are the most common and generally the most effective of all poisons.
HD03O
Airborne(AP)
HD04O
Airborne Powder poisons are those rare toxins that are taken into the body by being inhaled. There are only a few of these in existence.
HD03O
Gas(GS)
HD04O
Gas poisons are taken into the body by being inhaled. There are only a few of these in existence. Rarely are they carried in their natural state. Usually the materials needed to create them are carried and combined at the site of deployment.
HD03O
Special(SPC)
HD04O
Any of a variety of other paths that are truly out of the ordinary. 
HD02O
Type
HD03O
Death Dealing(DD)
HD04O
Death Dealing poison require the victim to roll a saving throw. If that saving throw is failed then the user will die at the end of he duration of the poison's effect.
HD03O
Paralytic(P)
HD04O
Paralytic poisons require a saving throw versus paralysation. If failed the character will be limited in action until the end of the poison's duration
HD03O
Damage(D)
HD04O
Damage doing poisons are the most common. They require a saving throw against poison. If the save is failed the character will take damage as detailed by the fifth element in the poison designation. The damage will be taken once per each basic time element. As an example, if a poison has a duration of 10 rounds and a damage of 1d6 then the character takes 1d6 of damage per round.  
HD03O
Hallucinogenic(H)
HD04O
Hallucination poisons are uncommon but often effective. If a save is made then the character is able to ignore the shades his made is throwing up on all sides of him. If he fails then his actions are slowed to half speed and he gets a minus in combat equal to 1/2 the amount he missed the ST by.
HD03O
Sleeping(SL)
HD04O
Sleep poisons are fairly straight forward. A ST is made at the onset of the poison. If failed the character falls asleep. The character is entitled to another ST at halfway through the duration. 
HD03ONC
Special(SPC)
HD04O
These are special effect poisons that have non-standard effects
HD02O
Onset Time
HD03O
As described in the Materials Designation 
HD02O
Duration
HD03O
As described in the Materials Designation 
HD02O
Potency Loss
HD03O
As described in the Materials Designation
HD02O
Damage 
HD03O
First Character # of die of damage
HD03O
Second Character set = size of die of damage
HD03O
and then a mod
HD03O
i.e. 2d12+1 = 2-24+1
HD01O
Insinuative Poisons Coats Per Dose
HD02O
Dart                    8
HD02O
Arrow                   4
HD02O
Dagger                  2
HD02O
Hand Axe                2
HD02O
Scimitar                1
HD02O
Spear                   1
HD02O
Pole Arm                1 Edge
HD02O
Short Sword             1 Edge
HD02O
Broadsword              1/2 Edge
HD02O
Bastard Sword           1/2 Edge
HD02O
Longsword               1/2 Edge
HD02O
T-sword                 1/3 Edge 
HD01O
Typically raw plant poisons are less effective and more subject to potency loss than poisons prepared from the plant.
