RV00000002
DL18
CO53
LN00
WM01
DD04
PF0080
PF0166
PF020
PF030
PF040
PF056
PF063
PF073
PF081
PF091
PF101
PF11
PF12
PF130
PF14
PF150
PF162
PF1732767
PF1815
PF194
PF201
PF211
PF221
PF231
PF2432767
PF251
HD01O
Description
HD02O
All of a Val-Tier's (Val-Tee-Air) physical statistics are generated using the procedure in Unearthed Arcana for Barbarians. The average Val-Tier is 8' (+ or - 6") Weight 270 lbs. They are a fairly dark skinned race with bleach blonde hair. 7% of all women are platinum blonde (y-linked recessive) They have a fairly high resistance to alcohol and are well adapted for great heights. 
HD01O
Physical Resources
HD02O
Noticeable Raw Materials
HD03O
The mountains of Val-Tier are relatively poor in mineral wealth and rich in plant and animal wealth
HD02O
Hidden Assets
HD02O
Neighboring Assets
HD01O
Technology
HD02O
The technological level of the Val-Tier is fairly primitive among most of the cultures of EA.
HD02O
They have metal workers capable of producing excellent steel but they are dependent on outside sources for Iron and Coal. 
HD02O
They possess simple fire starters and oil lamps.
HD01O
Subsistence Patterns
HD02O
The Val-Tier are a somewhat unique barbarian culture. They are both hunter/gatherers and farmers. They perform a simple form of terrace agriculture for a number of root stocks. They also cultivate various nut tress. 
HD02O
They hunt and take only the culls among the game of the area. Typically, they hunt deer, mountain sheep, bear, rabbit, boar, and sometimes buffallo on the plains north of the range.
HD01O
Values and Kinship
HD02O
The Val-Tier are an ancestor worship based culture. The believe that one's ancestors are the only spirits hat influence a man or womans fate. 
HD02O
They prize bravery, thrift, and cleverness. As a result they consider fighters and thieves to be equally honorable traits. They dislike assassins, not because of their techniques , but because they take money in order to kill.  
HD02O
They are a magic phobic culture. Shamans are respected (Somewhat) . MoonSingers and Dancers are respected. Druids are tolerated. Clerics are disliked and most mages can arouse intense hatred with little difficulty.
HD02O
They have few racial intolerences and a very few have been known to take grey elves as mates.(twice in the last two thousand years) 
HD02O
Despite their love of theives the culture is very polite. A man may leave even the most valuable belongings in a clan house and be assured of finding it there when he returns. Any who have eaten meat and drink with the tribe may claim "shared meat" sanctuary for a day and a night. 
HD01O
Language
HD02O
Language Tree
HD03O
They have their own language called Basque 
HD02O
Mapping
HD02O
Literacy
HD03O
Few of the Val-Tier can use the written version of the Val-Tier Those that can are tribal record keepers, shamans or wise women.
HD02O
Writing Forms
HD03O
A simple runic phonetic language
HD02O
Sounds
HD03O
Kul Hon Val San Han Jor Tay Hor Har Thol
HD02O
Vocabulary and Grammer
HD03O
Keehannah - Wise Women
HD03O
Chalket - Sister
HD03O
Tonhol - Brother
HD03O
Shiva - Warrior/Scout/Thief
HD03O
Shek - Scum
HD03O
Monhor - Kin Slaughterer
HD01O
Myths, and History
HD02ONC
The Val-Tier have a simple method of keeping 
HD01O
Cosmology and Dieties
HD01O
Tradition
HD02O
Wedding
HD02O
Bedding
HD02O
Birthing
HD02O
Battle
HD02O
Other
HD01O
Clergy
HD02O
Rites and Rituals
HD02O
Religious Norms
HD01O
Institutions 
HD01O
Art, Architecture, and Symbolism
HD02O
Symbolism 
HD03O
Common Motifs
HD03O
Significant Numbers
HD02O
Art
HD02O
Architecture
HD01O
Politics
HD02O
Leadership
HD03O
Stated
HD03O
Actual
HD02O
Class Controls
HD02O
Judicial Structure
HD02O
Legal Code
HD03O
Ownership of Goods
HD03O
Land
HD03O
Male and Female Roles
HD03O
Church and State
HD03O
Death
HD04O
By Suicide
HD04O
By Anothers Hand
HD04O
In Self Defense 
HD01O
Military
HD02O
Standing
HD02O
Command
HD02O
Routine
HD02O
Arms
HD02O
Outfitting
HD02O
Theory
HD01O

HD01O
The Val-Tier( Vale-Tee-yair ) nation is a matriarchal variation upon
HD01O
the Seneca long house nation. It is a total matriarchy with deep ancestral
HD01O
ties. ( Never pick on a Val-Tier's mother) 
HD01O

HD01O
Each clan is ruled by the Keehannah or wise mother. She is almost sacred 
HD01O
and to offer harm of any type to her is a death sentence. Within her
HD01O
hall: the long house, there is no fighting. It is considered an honor to
HD01O
be allowed to wear weapons into the long house. At the Keehannah's side is
HD01O
a shaman or Hounnah. The shaman is of mixed status for though he does not
HD01O
fight, sing or theive it is said that he may talk with impunity to the
HD01O
tribe's dead. (He can) The Back bone of the tribe is its scouts or
HD01O
Shiva's . Armed with the 6' Val-Tier whip sword and the 7'bows of the
HD01O
mountains they are an efficient hunting group in peace and a deadly army
HD01O
in time of war. The weapons unique to the Valtier are the whip sword,the
HD01O
great bow, and the Konjactal. 
HD01O

HD01O
Whipsword: require 6' SF 5 2-12/1-6
HD01O

HD01O
Greatbow: Warbow of the Val-Tier does a d8/d8   
HD01O

HD01O
The Konjactal: A three bladed folding throwing knife with the follow-
HD01O
ing properties:
HD01O

HD01O
1. May only be thrown
HD01O
2. On a miss of 5 or less (outside) it will return to the user.
HD01O
3. damage is a d3+2/d3+1  ranges: 1/2/3 
