RV00000002
DL21
CO51
LN00
WM01
DD03
PF0080
PF0166
PF020
PF030
PF040
PF056
PF063
PF073
PF081
PF091
PF101
PF11
PF12
PF130
PF14
PF150
PF162
PF1732767
PF1815
PF194
PF201
PF211
PF221
PF231
PF2432767
PF251
HD01O
Locales             Wind        Prec        Temp
HD02O
Hot             +00         +200        +250
HD02O
Warm            +00         +100        +125
HD02O
Temperate       +00         +00         +00
HD02O
Cool            +00         +00         -140
HD02O
Cold            +00         +00         -240
HD02O

HD01O
Month               Wind        Prec        Temp
HD02O
Cat             +00         +50         -200
HD02O
Hawk            +10         +75         -100
HD02O
Whale           +10         +25         -50
HD02O
Unicorn         +00         +00         +00
HD02O
Bear            -10         -25         +25
HD02O
Wolf            -20         -25         +50
HD02O
Pegasi          -05         +00         +00
HD02O
Griffon         +10         +10         -10
HD02O
Rat             +25         +30         -80
HD02O
Sphinx          +10         +40         -100
HD02O

HD01O
Land Formations     Wind        Prec        Temp
HD02O
Mtns
HD03O
Young       +100        +100        -75
HD03O
Old         +75         +50         -75
HD03O
Steppe      +50         +25         -55
HD03O
Mesa        +25         -20         +00
HD02O
Lowlands
HD03O
Hills       +00         +25         -20
HD03O
Valleys     +00         +10         +00
HD03O
Plains      +10         +00         +00
HD02O
Wet Lands
HD03O
Swamp       -30         +25         -10
HD03O
Marsh       -35         +15         -10
HD03O
Bog         -10         +00         -25
HD02O
Waterlines
HD03O
River Edge  +20         +10         -15
HD03O
Lake Edge   +25         +15         -25
HD03O
Sea Coast   +35         +35         -35
HD02O
Water
HD03O
River       +20         +15         -05
HD03O
Lake        +30         +00         -10
HD03ONC
Sea         +50         +00         -50
